### ISSUE TITLE
Can only add capability.Refresh Devices 

### ISSUE THREAD

**Issue by tonesto7** [pdlove/homebridge-smartthings#10]
The plugin itself works great.  Excellent work..
Using devices that support local execution like aeon multi-sensors don't have the refresh capability. 
I think it would be useful to split up the inputs for different devices.

**Comment by pdlove** [comment]
I'm going to add a group for anything with the "Sensor" Capability. This should take care of all reported devices that don't have refresh. I originally had a group for each capability, but it was a rather massive list even with the handful of devices I have.

**Comment by pdlove** [comment]
Please let me know if these show up with the latest commit of the SmartApp. It should work.

**Comment by tonesto7** [comment]
Thanks for the update... It doesn't appear to have worked.  I cleared the homebridge device cache and restarted from scratch in the app and the Multi-Sensors still aren't showing up.

**Comment by tonesto7** [comment]
After the last update they are working now
