### ISSUE TITLE
Activation code on app?

### ISSUE THREAD

**Issue by joq3** [pdlove/homebridge-smartthings#114]
Hi,

I have been using homebridge with homebridge-harmony plugin, but it isn't very stable. Someone suggested instead using the Harmony Hub with this smartthings-plugin instead. But I don't understand if I really need a Smartthing hub or if this plugin acts as the hub itself. Because when I launch the iOS app for the first time and log in to my account I setup with your application it asks for an activation code which you find on the hub.
As I haven't got any hub, where do I get the code from?

Thank you!

**Comment by pdlove** [comment]
This works with a smartthings account. I think the smartthings hub is requried.
