### ISSUE TITLE
Siri No Longer Works ("Sorry, I didn't hear back")

### ISSUE THREAD

**Issue by walksonair** [pdlove/homebridge-smartthings#126]
@pdlove , I have been working on why Siri will not control my locks and had opened an issue on the HomeBridge github page ([https://github.com/nfarina/homebridge/issues/1000#issuecomment-268557224](https://github.com/nfarina/homebridge/issues/1000#issuecomment-268557224)

Can the developer of homebridge-smartthings help in resolving what was found to be a new iOS 10.2 update to Siri where Siri sends the true/false commands to the lock but it's expecting an integer? I can paste the logs but it's in the link pasted above. Let me know how I can help resolve this...

**Comment by gijoecool** [comment]
@walksonair, I believe the issue is in lines 195-206 of smartthings.js

```
        thisCharacteristic.on('set', function(value, callback) {
                switch (value) {
                    case Characteristic.LockTargetState.SECURED:
                        that.platform.api.runCommand(callback, that.deviceid, "lock");
                        that.device.attributes.lock = "locked";
                        break;
                    case Characteristic.LockTargetState.UNSECURED:
                        that.platform.api.runCommand(callback, that.deviceid, "unlock");
                        that.device.attributes.lock = "unlocked";
                        break;
                } });
		that.platform.addAttributeUsage("lock", this.deviceid, thisCharacteristic);
```


`value` is being passed as true/false and the switch statement cannot handle that...

I think if you change the code to the following, then it should work. But you will need to test it for me. :)

```
        thisCharacteristic.on('set', function(value, callback) {
                if (value === false) {
                    value = Characteristic.LockTargetState.UNSECURED;
                } else if (value === true) {
                    value = Characteristic.LockTargetState.SECURED;
                }  
                switch (value) {
                    case Characteristic.LockTargetState.SECURED:
                        that.platform.api.runCommand(callback, that.deviceid, "lock");
                        that.device.attributes.lock = "locked";
                        break;
                    case Characteristic.LockTargetState.UNSECURED:
                        that.platform.api.runCommand(callback, that.deviceid, "unlock");
                        that.device.attributes.lock = "unlocked";
                        break;
                } });
		that.platform.addAttributeUsage("lock", this.deviceid, thisCharacteristic);
```

**Comment by walksonair** [comment]
@gijoecool, much appreciated! I just now have to find that file in my system...let me work on that.

**Comment by walksonair** [comment]
@gijoecool, yes, that did it! It is now working with Siri quite well. Thank you very much! Let me know how I can send you a cheery beverage!

![christmas-beer](https://cloud.githubusercontent.com/assets/15304664/21398675/06965998-c75d-11e6-848f-8881ce806dd5.jpg)

**Comment by gijoecool** [comment]
If you're ever near Richmond, VA (USA), then let me know and you can buy me a drink! ;)

**Comment by walksonair** [comment]
I will definitely do that and add you to my list of folks to thank on my USA tour. Cheers from Seattle, WA!

**Comment by gijoecool** [comment]
See #127.

**Comment by walksonair** [comment]
Thanks, I’m not too knowledgeable about GutHub (yet) but I verified that it
worked and documented that on your merge request on the site. Hope the
developer can accept so that when I go to update it doesn’t undo the fix.
