### ISSUE TITLE
icons not accessible for smartapp

### ISSUE THREAD

**Issue by fireheadman** [pdlove/homebridge-smartthings#135]
FYI:   Your code references icons that are in a restricted area, therefore nothing is displayed in ST for the icon. 

Could you put your icons in a public facing place please?    

iconUrl:   "https://dl.dropboxusercontent.com/s/7gy9a43mqhwf2xr/json_icon%401x.png",
iconX2Url: "https://dl.dropboxusercontent.com/s/nivk5n45yzz9c65/json_icon%402x.png",
iconX3Url: "https://dl.dropboxusercontent.com/s/y1q39zx4enki7wl/json_icon%403x.png",

![image](https://cloud.githubusercontent.com/assets/19847195/22362015/9c207c2e-e41c-11e6-86cc-0a9c424c6ba9.png)

**Comment by pdlove** [comment]
I'll get that fixed. To be honest, I'm not sure where I originally got the icons as it was copied from someone else's project originally... I really thought they were on AWS. As a warning, the icon will likely change because I don't remember what it looked like.

**Comment by fireheadman** [comment]
you are welcome to this icon...  https://github.com/fireheadman/ST/blob/master/homekit_icon.png?raw=true

![image](https://cloud.githubusercontent.com/assets/19847195/22389116/492900e2-e4a1-11e6-8b25-39efa8062f23.png)


I wasn't sure what your icon looks like, so I just found the homekit icon and plugged it into the code for now.   hopefully Apple doesn't have a cow about it.

**Comment by pdlove** [comment]
I've tried to keep the plugin agnostic to the actual homebridge project because I'm also using it for a data gathering project I've been working on. I e updated it to some combination or Json and SmartThings' logo that looks kinda cool.
Anyone who updates the app will get the new icon. There were no changes in the Smartapp that would break older versions of homebridge-SmartThings.

**Comment by fireheadman** [comment]
I actually like your new icon... I will be updating to use this code.
especially since you took the time to make the difference icon types... thank you very much!
