### ISSUE TITLE
Changes to the method used for device status updates

### ISSUE THREAD

**Issue by pdlove** [pdlove/homebridge-smartthings#136]
For anyone interested, the SmartThings plugin will have a number of changes to the way it communicates with SmartThings. If these changes won't work for any users in particular, please let me know and I'll talk to my contact at SmartThings about a better way to handle this. To be clear, these changes are occurring at the request of a SmartThings developer, so if you stay with the old plugin or set the thresh holds too low, they may disable your ability to use the smartapp.

There will be two methods to pick from for instant updates of item status:

1) The preferred method will be for homebridge-smartthings to get status updates directly from the hub. In this method, the startup process will send ip information to the cloud app and the hub will begin transmitting updates directly to your homebridge installation. The hub doesn't support receiving.... device change requests still go to the cloud.... for now.

2) The secondary method that I've added to the repository already is to use PubNub. Most users can use a free PubNub account to do this.

The current method will be kept but the default update interval will be set at 30 seconds with a 10 second minimum.
Please let me know any feedback.

**Comment by fireheadman** [comment]
unsure if this is related to the recent update you pushed out?
I am seeing a lot of these errors:

![image](https://cloud.githubusercontent.com/assets/19847195/22413235/558156ea-e673-11e6-8010-d0f453f09454.png)

**Comment by fireheadman** [comment]
UPDATE:   I am no longer see errors in IDE after applying your latest update.

**Comment by pdlove** [comment]
Good to hear. That was related to the Smartapp version 0.5.1. When I test... I really need to delete and recreate my app. It had an old value that was causing the error to not happen on my build.
