### ISSUE TITLE
Siri says "I didn't hear back" when I ask her to lock/unlock door

### ISSUE THREAD

**Issue by chevyman142000** [pdlove/homebridge-smartthings#137]
I have my 3 Schlage deadbolts connected via the SmartThings plugin to Homebridge. I can ask Siri for the status and she will tell me if they are locked or unlocked, but if I ask her to lock or unlock the door she says "I didn't hear back." All other switches that I have tried work fine, just the door locks are not working.

**Comment by pdlove** [comment]
@chevyman142000 Can you confirm if you are using the latest update from here or if you are using the latest npm version? It's working for me in development mode and I confirmed that home bridge is sending the command and then reporting back... not waiting for it to actually lock.

**Comment by chevyman142000** [comment]
Yes, running the latest version as I just installed it a few hours ago. I just checked NPM and it looks to be running 4.0.5. What and where are the logs that I could check to see if the command is making it to Homebridge?

**Comment by chevyman142000** [comment]
Had to specify update_method in config.json file to use direct.

**Comment by pdlove** [comment]
This has been resolved. The old API mechanism will no longer update fast enough due to SmartThings limitations.
