### ISSUE TITLE
Zen Thermostat - Device Results throwing unexpected error

### ISSUE THREAD

**Issue by alisdairjsmyth** [pdlove/homebridge-smartthings#14]
An unexpected exception is being throwing when rendering the Devices JSON for a **Zen Thermostat** when the device is in the `thermostatMode` is `off`:
`{"error":true,"type":"java.lang.NumberFormat Exception","message":"An unexpected error occurred."}`

Live Logging within SmartThings points to line 195 i.e. within the function `deviceAttributeList`.

If the `thermostatMode` is `heat` or `cool`, the same exception is not thrown.

The issue may be that the [Zen Thermostat Device Type](https://github.com/SmartThingsCommunity/SmartThingsPublic/tree/master/devicetypes/zenwithin/zen-thermostat.src) sets the `thermostatSetpoint` attribute to a string value `--` when the `thermostatMode` is `off`

**Comment by pdlove** [comment]
Any idea why it works like that? What is the difference between ... And off?

**Comment by alisdairjsmyth** [comment]
I presume it is for visual reasons. When the mode is off the setpoint has no meaning and represented within SmartThings App with the dashes.

Maybe you could add exception handling to set the attribute to null within your Map object in such circumstances?

When the thermostat is in the mode heat or cool, the setpoint variable has a numerical value e.g. 18.0. In these modes the setting of the value of the attribute in the Map object works.

**Comment by pdlove** [comment]
Thanks for the PR on this.
