### ISSUE TITLE
Version Check

### ISSUE THREAD

**Issue by animosity22** [pdlove/homebridge-smartthings#141]
I've tried a couple times, but if I refresh the code and look at the Version info on my mobile phone, it seems to always say

```
Version 0.4.1
```

I tried even deleting the app and redoing it from scratch today.

Am I missing something silly or is there a different way to validate I'm running the latest version?

**Comment by pdlove** [comment]
When you redid it from scratch, did you click "Publish"?
If so, I might be able to get some help for you from my Smartthings contact.

**Comment by animosity22** [comment]
I see this now and I was able to delete and remove it from my phone:

http://imgur.com/a/AJ35g

So I would think I published it properly as I had to redo my config with the new API keys and such.

**Comment by animosity22** [comment]
I'll chalk it up to something I did incorrect.

I tried one more time of cleaning everything out and removing it from my phone and redoing it again and I can see the latest version now. 

Apologies.
