### ISSUE TITLE
ST devices not being detected

### ISSUE THREAD

**Issue by flexyneat** [pdlove/homebridge-smartthings#143]
Hi,
I still consider myself a bit of a noob, but I set up homebridge on my macbook lastmonth nd it was working perfectly, but since i updated from the homebridge repo to v0.51, my smart things device arent being detected.

In the smartthings app, when i go to SmartApps > JSON Complete API > Device Results, i get the error below:
{"error":true,"type":"java.lang.NullPointerException","message":"An unexpected error occurred."}

and when i launch home bridge it echo's the same error:

[2/6/2017, 5:39:03 AM] [SmartThings] Initializing SmartThings platform...
[2/6/2017, 5:39:03 AM] [SmartThings] Fetching Smart Things devices.
[2/6/2017, 5:39:04 AM] [SmartThings] Error received type java.lang.NullPointerException - An unexpected error occurred.
[2/6/2017, 5:39:04 AM] [SmartThings] Unknown Capabilities: []
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
It worked fine all this while, this issue started after my update to 0.51 yesterday

**Comment by pdlove** [comment]
@flexyneat Still having this issue? It looks like an issue with the Smartapp. You should be able to update it and have the issue go away, but I'm not sure why you have that problem to begin with.

**Comment by flexyneat** [comment]
Yea, still having the issue. I also believe the problem is from the smart app because I Get the same error on my wife's iphone too when I click on SmartApps > JSON Complete API > Device Results. I'm just hoping the next update can resolve the issue for me.

**Comment by flexyneat** [comment]
I also deleted the smart app about 4times now and still get the same error when I add it back. Is there a way to revert to the older version of the smart app - 0.4x ? Because this problem started when I upgraded to 0.52

**Comment by pdlove** [comment]
The older versions no longer work reliably.
Can you try installing the smartapp so that only one device is selected? Something simple like a light..

**Comment by flexyneat** [comment]
HI,

Been kinda busy, but a few days ago, i started everything from scratch. uninstalled homebridge and all other plugins, and installed only homebridge and  homebridge-smartthings, but i still get the same error.And In the SmartThings app: SmartApps > JSON Complete API > Device Results gives:

![img_2784](https://cloud.githubusercontent.com/assets/24959941/23702340/1d849c2a-03fb-11e7-99c4-5aeb831850af.PNG)
<img width="917" alt="screen shot 2017-03-08 at 12 21 40 pm" src="https://cloud.githubusercontent.com/assets/24959941/23702346/23aa1968-03fb-11e7-8196-7ca93e715eaf.png">

**Comment by flexyneat** [comment]
going to http://homebridge-ip/accessories gives the result:

{"status":-70401}

**Comment by pdlove** [comment]
@flexyneat try this with the newest smartapp. It should get past the error now. You should be able to see the device causing the error in your smartthings logs as well.

**Comment by flexyneat** [comment]
I’m sorry, I forgot to mentioned that the error has been resolved for me. All works fine now


Thanks for your help

**Comment by arqjavier** [comment]
how you fix the error

**Comment by ShockUtility** [comment]
I have the same problem.
