### ISSUE TITLE
homebridge-smartthings stopped working two weeks after implementing the requested changes

### ISSUE THREAD

**Issue by pasilr1** [pdlove/homebridge-smartthings#159]
I followed all the instructions in  https://github.com/pdlove/homebridge-smartthings#device-updates-from-smartthings about three weeks ago and everything was working good. Since then I have rebooted all three (my raspberrypi which runs the homebridge-smartthings, my iPhone and my smartthings hub) and everything still worked after the reboot and the implementation of the changes. However last week without any change on any of the three devices, it stopped working: The Home app would not be able to detect the devices, Eve and Insteon+ did see them, and I could control them on either app but SIRI would not find them. I reset my HomeKit (deleted and recreated) and at that point the only change was that happened was that Eve and Instaeon+ could not find homebridge. I've contacted Smartthings and was told that they did not quarantine my app. To reiterate everything was working fine for about three weeks when it misteriously stopped working.

**Comment by pdlove** [comment]
So devices work in Eve/Insteon but Not Home or Siri?

**Comment by pasilr1** [comment]
Yes, but I tried to fix the problem by deleting my home from the home app and adding it again, and once I did that both Eve/Insteon as well as the Home app can see my hombridge.

**Comment by pdlove** [comment]
I hate to say it... If it's working in Eve or Insteon but not in Home then you may have an issue with your IOS device. 
What kind of devices do you have? I assume at least one light. I ask this because it's possible, though unlikely, that you only have devices not supported by Home? 
To start diagnosing this, I'd like to get a screen shot of what you're actually seeing in Home and Eve as well as the startup log from your Homebridge.

**Comment by pasilr1** [comment]
I have almost 40 devices and they have all been working fine for over a year,on Eve/Insteon and Home. They simply stopped working last week, first Home could not get a response from it and neither did Siri, but Eve/Insteon would see them and I could control then through the app. However once I deleted my home from the Home app I wasn't able to add the hombridge again to the Home app, (it couldn't find it), and Eve/Insteon lost it as well

**Comment by pdlove** [comment]
Did you kill the persist folder on homebridge? Once you unpair it from your phone you have to kill the persist folder to allow it to re-pair. It should be located with your config.json file in your .homebridge folder.
You might also kill the accessories folder in the same place.

**Comment by pasilr1** [comment]
I stopped hombridge, deleted the two files and rebooted the raspberrypi and problem was fixed. (coincidently a few minutes ago I got an email from Smartthings stating they had applied a hot fix to my hub, not sure if their fix did anything to help the situation).


Thank you.
