### ISSUE TITLE
Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by miabilabs** [pdlove/homebridge-smartthings#16]
Getting the following error, which is preventing Homebridge for launching. Any ideas?:

TypeError: Cannot read property 'location' of undefined
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:59:14
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:96:5
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:21)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by kdanthony** [comment]
I had the same issue today. When I looked the SmartApp was gone for some reason, I had to set it up in the SmartThings app again and fix the homebridge config for the new OAuth info. Not sure what happened but it's working again.

**Comment by miabilabs** [comment]
That doesn't seem to be the issue with me. The app is still there and OAuth is enabled.

**Comment by kdanthony** [comment]
The app was showing in the graph.api.smartthings.com for me just not in the phone as actually installed and automating. Might be worth removing and readding the smart app though as that error seems to just be its not getting the response back with the proper JSON and it isn't trapped.

**Comment by pdlove** [comment]
Make sure you have the latest version of the smart app installed.  It should show two groups of devices in the configuration, most devices and sensor devices.  If you see one called all devices, that is an older version.

**Comment by pdlove** [comment]
I had this happen today on my screen when I got home. I restarted home bridge and everything was fine. I'll look into better error handling on the refresh call.

**Comment by alisdairjsmyth** [comment]
I am experiencing the same issue as @miabilabs 

Implemented version of node packages:
`$ node -v`
`v4.2.1`
`$ sudo npm list -g homebridge`
`/usr/local/lib`
`└── homebridge@0.2.16`
`$ sudo npm list -g homebridge-smartthings`
`/usr/local/lib`
`└── homebridge-smartthings@0.0.2`

The attached file contains response body if I manually invoke the SmartThings devices API for my instance of the app.
[devices.json.txt](https://github.com/pdlove/homebridge-smartthings/files/124539/devices.json.txt)

**Comment by pdlove** [comment]
I just added a version number in the Smartapp. When you goto config, it should show version 0.3.
![fullsizerender](https://cloud.githubusercontent.com/assets/4213327/12968580/74e874ba-d039-11e5-982a-9c5e44d83b25.jpg)

**Comment by pdlove** [comment]
This also may be resolved by my improved error trapping.

**Comment by alisdairjsmyth** [comment]
After installing the new version of the Smartapp - I am no longer experiencing this issue.

**Comment by pdlove** [comment]
I'm confident that we've got this resolved and am closing the issue.
