### ISSUE TITLE
JSON Complete API App does not open when started

### ISSUE THREAD

**Issue by berndgill** [pdlove/homebridge-smartthings#160]
Hi,
I have a European hub, therefore I have to copy the JSON code in the code window to install the app on the SmartThings Hub.With the previous version I had no problem, but since Smartthings blocked the old app version I deleted all old code and reinstalled it.

I can then also install the App in the Smartphone App. But when I click to open it, it is loading but never opening. What did I do wrong?

**Comment by pdlove** [comment]
On the smart things site please have the Live Logging page up and then try opening it. Let me know if it shows any errors associated with the smart app.

**Comment by berndgill** [comment]
OK now it is working.

The first issue was OAuth needed to get activated in the "My SmartApps" Tab for the pdlove JSON Complete API app after creating it as new smart app from code.

The second issue was the config.json file on my mac server running home bridge.

As this took my quite some time to figure out what needs to get added / changed from what is described in the installation description in GitHub I copy my config.json file below.

Important this is for the European version of the SmartthingsHub!

You need to Replace SMARTTHINGSHUBMACADDRESS, APPID, ACCESSTOKEN by your specific values tomato it work.
I changed at a certain point also the pin and the port (but I'm not sure if this is really required).
If you had the old version of the app installed I also recommend to completely delete the HOME app on your IOS device and reset it up, as it still showed part of the old installation 

{
	"bridge": {
		"name": "Homebridge",
		"username": "SMARTTHINGSHUBMACADDRESS",
		"port": 51827,
		"pin": "031-45-155"
	},
	"description": "JSON API",
	"platforms": [{
		"platform": "SmartThings",
		"name": "SmartThings",

		"app_url": "https://graph-eu01-euwest1.api.smartthings.com:443/api/smartapps/installations/",
		"app_id": "APPID",
		"access_token": "ACCESSTOKEN "
	}]
}

**Comment by pdlove** [comment]
The user name does not have to be the mac address of the hub. It is just a generic mac address used for authentication to HomeKit.
