### ISSUE TITLE
json complete api stuck at version 0.4.1 in app

### ISSUE THREAD

**Issue by themattharris** [pdlove/homebridge-smartthings#162]
after updating homebridge-smartthings at https://graph.api.smartthings.com i can see that it has version 0.5.2 published. i can tell this because viewing the application includes this line "paragraph "Version 0.5.2"".

however, when i go to "automation" and then "my apps" in the smartthings app and chose JSON complete api it reports version 0.4.1. i'm using an iphone 7.

because the version reports as 0.4.1 smartthings keeps rate limiting, and thus disabling the plugin from functioning every 3-4 days. 

any ideas why the smartthings website reports 0.5.2 but the app says 0.4.1? i've removed smartthings from my phone and reinstalled it. logged out and logged in. deleted all apps from "my smartapps". disconnected github and reconnected it. installed and reinstalled multiple times.

thanks!

**Comment by bojanrajkovic** [comment]
I ran into the same issue. Click the magnifying glass in the left column on https://graph-na02-useast1.api.smartthings.com/ide/apps (or whatever your smartapps URL is), and then overwrite your local version with the GitHub version.

**Comment by themattharris** [comment]
yeah in my case i found the issue was the https://graph.api.smartthings.com is *not* the correct IDE for my hub. instead i should have been using https://graph-na02-useast1.api.smartthings.com. annoyingly this took a while to figure out because removing plugins from the wrong IDE did remove them from my app, even if upgrading them did nothing.

for anyone else if you're not sure which IDE to use go to any of them, login, them click "my locations". select yours and you'll be taken to the correct IDE for your hub.

after that an uninstall and reinstall as per the guidance for the upgrade worked.
