### ISSUE TITLE
Homebridge stops working with plugin

### ISSUE THREAD

**Issue by macjeff** [pdlove/homebridge-smartthings#166]
I tested this last weekend (a week ago) and finally stopped for now.  I forgot to post this.

I see a similar issue posted almost exactly a year ago!!! (https://github.com/pdlove/homebridge-smartthings/issues/58)

But when I install the plugin, homebridge devices all stop reporting and although it seems to be running fine I cant get any update on device.

The bad thing is the ONLY way I have found to stop this issue is to npm Uninstall the plugin.   

I did many times but the issue is each time I have to delete and resetup my homekit which means losing all the devices in rooms, etc and I have LOTS of devices.

The only other plugins I have are ISY, Ecobee Sensors, Lockitron, and Netamo.  They all work fine- well until I install this one.

This happens without even editing the config.jsn for this plugin so I am really stumped and just gave up.  I will try it again if there are some exact logs you want or anything.  I just hate to have to do the homekit setup again but I will.

One idea I have is the devices I was passing through could be causing something or an issue in my app.  If you are willing to help and message me off this page I can give you temp access to the systems to look at.

Jeff

**Comment by pdlove** [comment]
Are your referencing the callback error? If so, please post the error log so that I can see which grouping is causing it.
I recommend that home bridge be run so that platforms that have alot of accessories get their own bridge. I run mine like this with multiple config folders... one for Wink, one for Smartthings and one for the other odds and ends. The iPhone has to be joined to all three hubs separately, but it limits the devices that might have issues.

**Comment by macjeff** [comment]
I reinstalled everything from scratch and did not install any plugns I did not use anymore.  Working ok so you can close this BUT  I have a few devices not working.   

1. Samsung Refrigerator- part of the Samsung Home stuff.   Its basically a sensor saying door open or closed.  It sees it but no data coming in.

[3/20/2017, 2:27:13 AM] [SmartThings] Device Added - Group sensor, Name Refrigerator, ID d0fac164-b7e9-419f-a676-9ac56bbc7985
[3/20/2017, 2:27:13 AM] [SmartThings] Unknown Capabilities: ["Consumable"]
[3/20/2017, 2:27:13 AM] [SmartThings] Initializing platform accessory 'Refrigerator'...
[3/20/2017, 2:27:13 AM] [SmartThings] Direct Connect Is Listening On xxxxxxxx


2.  These are sensor devices....dont laugh.but egg trays that tell you if your out of eggs or if they are old.  Data looks good but skipping them.   I think if you set it up like a multi sensor with three choices-   Total Count.   Fresh.   Expired.   I can send a screenshot of how it looks in smart things if that helps

Device Skipped - Group unknown, Name Egg Miser, ID f5cf1548-1007-4217-8c6d-e04047c1eba1, JSON: {"name":"Egg Miser","basename":"Egg Miser","deviceid":"f5cf1548-1007-4217-8c6d-e04047c1eba1","status":"ACTIVE","manufacturerName":null,"modelName":null,"lastTime":"2017-03-20T05:11:03+0000","capabilities":{"Polling":1,"Refresh":1},"commands":{"poll":[],"refresh":[],"eggReport":[]},"attributes":{"inventory":"goodEggs","totalEggs":"1","freshEggs":"1","oldEggs":"0","eggReport":null}}
[3/20/2017, 2:16:54 AM] [SmartThings] Device Skipped - Group unknown, Name Egg Miser 2, ID 7cc4ea6d-4e4c-4b74-a1ca-c2a56cea9a55, JSON: {"name":"Egg Miser 2","basename":"Egg Miser 2","deviceid":"7cc4ea6d-4e4c-4b74-a1ca-c2a56cea9a55","status":"ACTIVE","manufacturerName":null,"modelName":null,"lastTime":"2017-03-20T04:04:03+0000","capabilities":{"Polling":1,"Refresh":1},"commands":{"poll":[],"refresh":[],"eggReport":[]},"attributes":{"inventory":"goodEggs","totalEggs":"1","freshEggs":"1","oldEggs":"0","eggReport":null}}


3. Honeywell Total Connect Alarm-   It has 3 choices and status.  Arm Away, Arm Stay, Unarm and status of Armed or Unarmed.
It never shows up in home app.

[3/20/2017, 2:33:50 AM] [SmartThings] Device Added - Group locks, Name Total Connect Alarm, ID 23b533d3-1d2f-44e1-8e4a-bb4305c1e17d
[3/20/2017, 2:33:50 AM] [SmartThings] Initializing platform accessory 'Total Connect Alarm'...
[3/20/2017, 2:33:50 AM] [SmartThings] Direct Connect Is Listening On XXXXXXXXX
[3/20/2017, 2:33:50 AM] [SmartThings] SmartThings Hub Communication Established

**Comment by macjeff** [comment]
Update- I figured out the initial problem (which came back)  If you look at my last response, its the Honeywell Total Connect that is causing the issue.  I turned that off for syncing and its fine. But turn it on and not only does the app loose connection to homebridge but you have to wipe the Persists folder and re-connect to get it to work again (after removing the honeywell syncing).  But we are good for now.   I can do wihtout it in homebridge if you cant fix it.  If you fix the stuff above, everything else works...

thanks,

Jeff

**Comment by animosity22** [comment]
I'm actually in the same boat. I've been working for quite some time, but my only common thing is the TCC plugin.

I've disabled that yesterday and things seem smooth now.

I am not getting any errors in the logs that I can tell and everything just goes Unresponsive.

**Comment by Klynn7** [comment]
Just to add my +1, I have a new install of Homebridge, with this being the only plugin it's ever had, and it will periodically crash and stop responding.  If I stop and restart Homebridge everything is fine for a bit until it breaks again.

The only devices I have attached to my SmartThings are GE dimmers and switches.

If it helps, it seems asking Siri to turn of the lights in two separate rooms is pretty much a guaranteed way to crash it, though it seems to randomly crash otherwise periodically.

**Comment by pdlove** [comment]
@Klynn7 can you get me a log of the crash? I've been running non-stop for almost 2 months now on my RPi.

**Comment by Klynn7** [comment]
/var/log/homebridge.log and /var/log/homebridge.err are both empty.  I'm running Homebridge as a service so I'm guessing it's logging elsewhere, but I can't find it. (It appears the logs, if it even creates them, are not named homebridge.log or homebridge.err)

I'll run the process manually and see what I can gather.

**Comment by pdlove** [comment]
Mine ends up logging in /var/log/messages. It's annoying but I don't understand the systemctl setup enough to fix it.

**Comment by Klynn7** [comment]
I don't appear to have a /var/log/messages?

**Comment by pdlove** [comment]
If you're using systemctl, you might also get it like this: "journalctl -u homebridge" assuming the service name is homebridge.

**Comment by Klynn7** [comment]
I tried that but I restarted the service today (in messing around trying to find the logs) and all I'm seeing is the standard startup stuff.  I have it running in a console session now so I'll let you know what the logs say next time it blows up.

**Comment by animosity22** [comment]
So for logging, you can use something simple like this as it's rsyslog on Ubuntu that does the logging:

```
root@plex:/etc# cd rsyslog.d/
root@plex:/etc/rsyslog.d# ls
20-ufw.conf  30-homebridge.conf  31-rclone.conf  32-influxdb.conf  35-router.conf  50-default.conf  postfix.conf
root@plex:/etc/rsyslog.d# cat 30-homebridge.conf
$FileCreateMode 0644
if $programname == 'homebridge' then /var/log/homebridge.log
& stop
```

So it writes my homebridge logging to /var/log/homebridge.log and stops there and doesn't output it anywhere else.

My systemd looks like:
```
root@plex:/etc/systemd/system# cat homebridge.service
[Unit]
Description=Homebridge
After=network.target
RequiresMountsFor=/data

[Service]
ExecStart=/usr/bin/homebridge
Type=simple
GuessMainPID=no
User=felix
Group=felix
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

**Comment by Klynn7** [comment]
Hey @pdlove I actually have not had the crash since I messed with this to get it logging, so I guess the issue solved itself?

Thanks for the help, though!
