### ISSUE TITLE
GE Smart Dimmer Switch

### ISSUE THREAD

**Issue by curtispaul** [pdlove/homebridge-smartthings#169]
Hi, 
I recently added a GE Z-Wave Dimmer Switch to smartthings but when launching homebridge says it has "Unknown Capabilities".  It's device type in smartthings is just a generic dimmer switch, so I'm not sure why it wouldn't work.  If I try changing the device type, I lose functionality. 

Anyone have any thoughts?

**Comment by pdlove** [comment]
What model? I use GE Zwave dimmers with no problem although someone recently had a reported issue with Cree bulbs. I'm wondering if SmartThings changed the capabilities on new additions..

**Comment by curtispaul** [comment]
I have model #12724.  Thanks!

**Comment by curtispaul** [comment]
For anyone else having this issue, you need to turn off the SmartThings default health check option inside your ST app.  Once I did that and relaunched homebridge, my device showed up.  @pdlove, thanks for the recent changes to include more error info, that's what tipped me off!

**Comment by pdlove** [comment]
Glad to hear it. But that still confuses me because I have health check enabled and am not having problems with my dimmers.
