### ISSUE TITLE
Icon links broken

### ISSUE THREAD

**Issue by swtaylor** [pdlove/homebridge-smartthings#178]
These three links are broken:
    iconUrl:   "https://dl.dropboxusercontent.com/u/17876795/JSON%401.png",
    iconX2Url: "https://dl.dropboxusercontent.com/u/17876795/JSON%402.png",
    iconX3Url: "https://dl.dropboxusercontent.com/u/17876795/JSON%403.png",

wget https://dl.dropboxusercontent.com/u/17876795/JSON%401.png
--2017-04-27 04:19:56--  https://dl.dropboxusercontent.com/u/17876795/JSON%401.png
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.1.6
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.1.6|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-27 04:19:56 ERROR 404: Not Found.

**Comment by pdlove** [comment]
Does anyone have a recommendation on a place to upload pictures? For some reason these stopped sharing on my dropbox.

**Comment by swtaylor** [comment]
Is there any reason they couldn't be uploaded to github, with links to the raw file?

**Comment by pdlove** [comment]
Because that answer is too obvious. 😄

**Comment by jelockwood** [comment]
Could you post the new GitHub hosted URLs? This should allow manually editing an installed copy in the namespace section to use the new URLs without all the hassle of a full update. (Correct me if not true.)

**Comment by pdlove** [comment]
The Smart-App update should be the same as if you manually did it. You simply login on smartthings and select "Update from repo". Make sure to check the box "Update from Repo" when you do that. Also, make sure you only select the Groovy file.
