### ISSUE TITLE
Bluetooth?

### ISSUE THREAD

**Issue by jelockwood** [pdlove/homebridge-smartthings#179]
Whilst the Smartthings v2 hub has built-in Bluetooth hardware they have not yet seen fit to enable this.

I am presuming there is no way for Homebridge to ignore ST and simply utilise the Bluetooth hardware?

The reason I raise this is because as people will know HomeKit devices can be either WiFi devices, or Bluetooth devices. Obviously Homebridge can easily contact WiFi devices as simple IPv4 traffic over the LAN but I am assuming Homebridge would have problems contacting Bluetooth devices especially as the host environment i.e. a Smartthings Hub v2 currently does not enable Bluetooth.

In particular I would like to utilise the forthcoming Danalock v3 (with HomeKit) which will be a Bluetooth only device.

Other than the current presumed impossibility of using the Smartthings hubs own Bluetooth, another approach has occurred to me. ConnectSense have announced a Bluetooth 'extender' which also acts as a Bluetooth hub linking devices to their LAN and is particularly aimed at HomeKit devices. See https://www.connectsense.com/products there is also an announced similar product from Elgato called the Eve Extend. Actually thinking about it in my case the Elgato Eve Extend will make more sense even if functionally identical because it will be more likely to offer UK/EU power supplies.

Examples of already shipping Bluetooth HomeKit devices include the following -

Elgato Eve Weather Outdoor
Elgato Eve Room Indoor
Elgato Energy
Fibaro HomeKit sensors
August Smart Lock
Schlage Sense lock
Danalock v3 - when shipped

and so on.

**Comment by pdlove** [comment]
To clarify, the request here is backwards and is to extend support for integrating Bluetooth HomeKit devices  into Smartthings. I'm actually working on a project to expose HomeKit devices back to homebridge and, eventually, expose homebridge plugins to Smartthings. That is a very longterm project that could help do this. I would guess it to be the end of the year before I have any of that working.

**Comment by jelockwood** [comment]
Thank you for the clarification and notice of your plans. I wish you the best of success and may later be in a position to assist with testing.
