### ISSUE TITLE
platform name conflicts with SmartThings plugin in the homebridge-legacy-plugins package

### ISSUE THREAD

**Issue by surfous** [pdlove/homebridge-smartthings#19]
HomeBridge fails at start when homebridge-legacy-plugins is installed with homebridge-smartthings, and the config stanza in the homebridge-smartthings README.md is used as the basis for configuration. No stanza remained in my config.json for the legacy plugin. 

Both plugins will consume the stanza for platform "SmartThings," though so HomeBridge startup fails. 

The solution is just a small change in config that should be reflected in the instructions. Doing this will not hurt even if you don't have homebridge-legacy-plugins installed. 

Instead of
```
{
    "platform": "SmartThings",
```

preface it with the plugin name to disambiguate the namespace:
```
{
    "platform": "homebridge-smartthings.SmartThings",
```

and you're good! No changes needed to either plugin package.

**Comment by rickybloomfield** [comment]
I ran across this as well. If you need to keep the legacy plugins, the above suggestion is the way to go (and the error message provides these instructions as well). If you're not using the legacy plugins for anything else, it's probably best to remove them:

```sudo npm rm -g homebridge-legacy-plugins```

**Comment by pdlove** [comment]
I'm also going to be submitting a PR to remove the smart things plugin from the legacy when I've got most of the current issues resolved.

**Comment by miabilabs** [comment]
Is it rm or uninstall to properly remove plugins? I thought this was doing it for me:

sudo npm uninstall -g homebridge-legacy-plugin

**Comment by rickybloomfield** [comment]
I had tried ```uninstall``` first but it didn't work for me. But ```rm``` worked. No harm in trying either!
