### ISSUE TITLE
Unable to fetch smartthings devices to Homebridge

### ISSUE THREAD

**Issue by gurastelli** [pdlove/homebridge-smartthings#196]
I have installed Homebridge on my Rpi and followed all instructions. I also have JSON API version 0.5.5 on my iphone, yet I can't seem to fetch any smartthings devices.  I have updated/published the API, Homekit detects homebridge but it's grayed out due to no devices listed. Your help would be appreciated, I'm first time user and learning pretty quickly, but stuck on this. See my config.json and also the errors message:

{
    "bridge": {
        "name": "Homebridge",
        "username": "B8:27:EB:AB:4C:AB",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "JSON API",
    "platforms": [
        {
            "platform": "homebridge-smartthings.SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
            "access_token": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
"polling_seconds": 3600,
"update_method": "direct",
"direct_ip": "192.168.0.45",
"direct_port": 8000,
"api_seconds": 30
        }
    ]
}

pi@raspberrypi:~/.homebridge $ 
pi@raspberrypi:~/.homebridge $ 
pi@raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-7-19 19:10:07] Loaded plugin: homebridge-smartthings
[2017-7-19 19:10:07] Registering platform 'homebridge-smartthings.SmartThings'
[2017-7-19 19:10:07] ---
[2017-7-19 19:10:07] Loaded config.json with 0 accessories and 1 platforms.
[2017-7-19 19:10:07] ---
[2017-7-19 19:10:07] Loading 1 platforms...
[2017-7-19 19:10:07] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[2017-7-19 19:10:07] [SmartThings] Fetching Smart Things devices.
[2017-7-19 19:10:08] [SmartThings] Error received type undefined - undefined
[2017-7-19 19:10:08] [SmartThings] Unknown Capabilities: []
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-7-19 19:10:08] Homebridge is running on port 51826.
[2017-7-19 19:10:08] [SmartThings] Direct Connect Is Listening On 192.168.0.45:8000

**Comment by pdlove** [comment]
If you go into the Smartapp and scroll down to "Config" is that the URL you're given? Usually in the US the URL is just graph.api.smartthings.com and not the exact region's url.

**Comment by gurastelli** [comment]
yes, that is what I have on my API. Unless there is a different one, I'm going to delete and publish it again. I'll let you know.

**Comment by gurastelli** [comment]
yup, that did it. I removed the JSON API from Smartapps, re-installed it. I noticed the app_id and access_token were different on the new one (app_url still showing na02-useast1)
After updating Homebridge and changing to new values then it started working like a champ. Thanks a bunch! Awesome work!
