### ISSUE TITLE
Constant error received...

### ISSUE THREAD

**Issue by tonesto7** [pdlove/homebridge-smartthings#21]
Homebridge shows this error constantly after initializatio 
`[SmartThings] Error received type RateLimit - Please try again later`

Under ST logs it's nothing but this 
`physicalgraph.app.exception.SmartAppException: Device not found @ line 158`

**Comment by tonesto7** [comment]
Looking through the code it looks like you are only looping through the deviceList input and not the sensorList as well.

**Comment by pdlove** [comment]
Line 68 of index.js calls device population on the sensor list.
Are you still getting the other crazy errors?

**Comment by tonesto7** [comment]
Yes i am still getting them. 
I can however still control the devices after api rate limit resets.

**Comment by humac** [comment]
I also see this error.

**Comment by pdlove** [comment]
Do y'all have anything else hitting the Smartthings API? I'm only able to duplicate this by having two computers with this plugin running at the same time. You can try adding "polling_seconds": 20 to increase the delay between polls and see if that clears it up. I've been thinking through how to use subscriptions to eliminate the need for polling. no ETA yet.

**Comment by tonesto7** [comment]
i added the polling_seconds to the config and rebooted.
It's only using the one app.

It's trying to query/update all of the devices too quickly in rapid succession every 20 seconds.

`fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:35:50 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159`

`fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  9:36:10 AM: error physicalgraph.app.exception.SmartAppException: Device not found @ line 159`

**Comment by pdlove** [comment]
I just committed a fix for this. I'm now able to get my polling rate down to 2 seconds on my Raspberry Pi and not get any errors. Moving it below 2 seconds is simply running up against and issue on how long it takes Smartthings to build the json for all devices.
I'm adding a few more little features and will do a new npm release tomorrow night or Saturday morning.

**Comment by tonesto7** [comment]
thats interesting because all of the errors were coming from the deviceQuery() method of the app. When I looked into it.  I realized that when the homebridge queried the sensors there was no reference to the sensorList in the deviceQuery... I submitted a pull request which may be unnecessary now.

**Comment by pdlove** [comment]
I'm going to go ahead and Close this one. @tonesto7 can you fix up your icon on the PR so I can suck it in? It definitely contains a fix to an issue.

**Comment by allanak** [comment]
I'm going to request reopening this. I get the same issue (line 182 now) on the most recent version with polling interval set to 20 seconds.
`def deviceQuery() {
	def device = findDevice(params.id)    
    if (!device) { 
        device = null
**        httpError(404, "Device not found")
**    } `

**Comment by dtydings** [comment]
I know this thread is closed but the issue just came back for me even though I have polling seconds set to 60. 
There is another value now as well though called update seconds right below polling seconds in my config also set to 60. 

This is as far is it gets when I start homebridge:

[SmartThings] Error received type RateLimit - Please try again later
[SmartThings] Unknown Capabilities: []
[SmartThings] Direct Connect Is Listening On 192.168.0.189:8000


It doesn't even attempt to query/update any devices. This started happening after I updated node.js to the latest release but strangely enough it was working just fine for little while after the update.

Any help would be very much appreciated! Thank you!
