### ISSUE TITLE
2 switches are showing up as bulbs in homekit

### ISSUE THREAD

**Issue by xxKeoxx** [pdlove/homebridge-smartthings#219]
I have 2 zwave switches that are showing up as bulbs in home kit.  One is a dimmer and the other is not.  I verified the devices are using the same device type as other switches that are showing up as switches in home kit.  Any advice on how to trouble shoot this?  I would like to get this fixed because my OCD is going nuts. :-)

**Comment by LeBlaaanc** [comment]
@xxKeoxx I'm having this happen but oddly only recently and not with all the bulbs... As a solution we might be able to use something like Trendsetter to trick homekit/homebridge into thinking it's a dimmer, I'm trying now.

**Comment by LeBlaaanc** [comment]
@xxKeoxx I figured it out this evening, for whatever reason the GE Link device handler doesn't have the Light capability. Simply create a new device handler from the GE Link Bulb template and add `capability "Light"` to that capability list. I'm baffled as to why this isn't listed as a capability honestly.
