### ISSUE TITLE
Power Meter / Energy Meter Capability Devices

### ISSUE THREAD

**Issue by kdanthony** [pdlove/homebridge-smartthings#23]
Device with the 'Power Meter' and 'Energy Meter' capability getting skipped. Aeon Labs DSB09104-ZWUS home energy meter. Skipped line from logs:

`[homebridge-smartthings.SmartThings] Device Skipped - Group unknown, Name Power Monitor, ID 7d6a876f-e3ba-49c0-9f8b-fbc52aaa6922, JSON: {"name":"Power Monitor","deviceid":"7d6a876f-e3ba-49c0-9f8b-fbc52aaa6922","capabilities":{"Configuration":1,"Energy Meter":1,"Power Meter":1,"Sensor":1},"commands":{"configure":[],"reset":[]},"attributes":{"energy":13234.588,"power":1996}}`

**Comment by pdlove** [comment]
I've ordered one of these for my home. I also found the Characteristics EVE uses in HomeKit at this page: https://gist.github.com/gomfunkel/b1a046d729757120907c
This will allow us to have it at least display in an app once it's in place.
