### ISSUE TITLE
Certificate has expired?

### ISSUE THREAD

**Issue by arlorose** [pdlove/homebridge-smartthings#234]
Running this today, I got:
```
[2018-1-28 00:03:30] Homebridge is running on port 51826.
[2018-1-28 00:03:30] [SmartThings] Direct Connect Is Listening On 192.168.1.133:8000
error at req:  certificate has expired
```
I poked around and added a `"verify_ssl": false` to the platform config entry, but that didn't work.

Weird coincidence... I'm also getting a site not secure error on SmartThings right now. Maybe that's related?

**Comment by Quiqui64** [comment]
I believe Smartthings has a outage right now https://status.smartthings.com/

**Comment by arlorose** [comment]
Yeah, I was coming back to note that. :-)
