### ISSUE TITLE
Thermostat - Smartthings state not consistent with Homekit

### ISSUE THREAD

**Issue by alisdairjsmyth** [pdlove/homebridge-smartthings#24]
The state of the thermostat as reported through Smartthings is not being reflected in Homekit enabled App.

Within Smartthings, the thermostat has the following state:
- Current Temp: 23.2
- Setpoint: 18.0
- Fan Mode: Auto
- Mode: Heat

Within Homekit enabled App, the same thermostat has the state:
- Temperature: 0.0C
- Heating Threshold: 0.0C
- Cooling Threshold: 10.0C
- Mode: Off

Manually invoking the API returns (abbreviated body):
`{`
`    "location": {`
`        ...`
`        "temperature_scale": "C",`
`        ...`
`    },`
`    "deviceList": [`
`        {`
`            "name": "Zen Thermostat",`
`            "capabilities": {`
`                "Temperature Measurement": 1,`
`                "Configuration": 1,`
`                "Refresh": 1,`
`                "Thermostat": 1,`
`                "Sensor": 1,`
`                "Actuator": 1`
`            },`
`            "commands": {`
`                ...`
`            },`
`            "attributes": {`
`                "temperature": 23.2,`
`                "heatingSetpoint": 18,`
`                "coolingSetpoint": 18,`
`                "thermostatSetpoint": 18,`
`                "thermostatMode": "heat",`
`                "thermostatFanMode": "fanAuto",`
`                "thermostatOperatingState": "idle",`
`                "schedule": null`
`            }`
`        }`
`    ],`
`    "sensorList": []`
`}`

Environment:
- Thermostat: Zen Thermostat
- Homebridge: 0.2.16
- Homebridge-Smartthings: 0.0.2
- Homebridge-Smartthings SmartApp: 0.3
- Smartthings Temperature Scale: Celsius
- App: Eve

**Comment by alisdairjsmyth** [comment]
A couple observations in `accessories/smartthings.js`:
- Calculation of `temp_requested` includes the following logic for a couple cases of `thermostatMode` values `temp_requested = (that.device.attributes.heatingSetpoint + that.device.attributes.heatingSetpoint) / 2;` which is the equivalent to y=2x/2 or y=x or in this case `temp_requested = that.device.attributes.heatingSetpoint`
- Handling of Temperature Measurement capability does not include logic for different temperature scales
- I am not convinced `platform.temperature_unit` has a value `C` - and therefore the fahrenheit calculation is being applied

**Comment by pdlove** [comment]
I'm about to switch my Smartthings to Celsius and double check every thing.

**Comment by pdlove** [comment]
It looks like you are correct that platform.temperature_unit doesn't get set to C correctly. 
I'm also fixing the other item. When set to Auto,  it is supposed to be using heating and cooling set points to get the average.  I'll have a revision published tonight that fixes all the issues with Celsius and adds a few more things.

**Comment by alisdairjsmyth** [comment]
Original issue looks to be resolved.  State is consistent between Smartthings and Homekit.
- Heat Setpoint is accurate
- Cooling Setpoint is accurate
- Current Temperature is accurate
- Mode is accurate

Environment:
- Homebridge-Smartthings: 0.3.5
- Homebridge-Smartthings SmartApp: 0.3.6
- Smartthings Temperature Scale: Celsius
