### ISSUE TITLE
Issues with settings on the Smart App

### ISSUE THREAD

**Issue by coolcom** [pdlove/homebridge-smartthings#28]
The following doesn't really work/make sense:
Click on Settings and add the repository with Owner of "pdlove" and name of "homebridge-smartthings" and branch of "master" and then click save.
Click "Update From Repo" and select "homebridge-smartthings"

There is no option for the repository or any of this on the Smart app. I'm not sure how to get this.

**Comment by humac** [comment]
@coolcom those steps are not on the SmartApp.  Those are the steps you perform in the IDE to install the smartapp. 

You need to login to the IDE via your web browser.
https://graph.api.smartthings.com/ide/apps

**Comment by coolcom** [comment]
that is where I am. I don't have any settings option. I clicked "+New smartapp" and pasted the code from https://github.com/pdlove/homebridge-smartthings/blob/master/smartapps/pdlove/json-complete-api.src/json-complete-api.groovy

Is there another way I should be doing this?

(I am pretty technically savvy and have installed other custom smartapps before, but none requiring a git repo)

**Comment by humac** [comment]
You need to click the "Enable GitHub Integration" and follow the steps to install via your github account.  Also you can always manually install the smart app via the copy & paste method you are probably used to...

**Comment by humac** [comment]
Grab the code here https://github.com/pdlove/homebridge-smartthings/tree/master/smartapps/pdlove/json-complete-api.src

**Comment by coolcom** [comment]
I tried enabling github integration but got a 404 from GitHub when clicking
the link to sync my acct. I will try again in a little bit.

When I copy and pasted code, published, etc. I was able to install it on my
phone, but when I tap on the installed app, under things - smart
apps, nothing happens.

Thanks for your help, by the way.

**Comment by humac** [comment]
Oh sorry i didn't read your response completely :) If you did the copy & paste method then you can skip the GitHub stuff where the "settings" button would appear.  Yeah ST has some bugs with GitHub integration aswell.  You did all the right steps to install manually.  I think there is a bug with the latest code and it maybe temporarily broken... 

See this open issue:
https://github.com/pdlove/homebridge-smartthings/issues/27

**Comment by coolcom** [comment]
It's ok, no problem. Thanks for the update. I will sit tight for an update
to the code.

**Comment by coolcom** [comment]
Thanks again for the help. I realized I needed to create a repo on my Git (brand new to Git) called "SmartThingsPublic" to get it to work. So that is progress.
