### ISSUE TITLE
The switch it not showing as a switch or any device

### ISSUE THREAD

**Issue by julianfez** [pdlove/homebridge-smartthings#3]
![](http://i.imgur.com/657P0qD.jpg)

**Comment by julianfez** [comment]
All the devices that i have with SmartThings appear like this i did everything u said , plus one step i dont know if its the problem and i enable the Auth on SmartThings

**Comment by pdlove** [comment]
Basically the device is showing up but with no function? It looks like I'm dealing with a switch in most cases... Just not when it really is just a switch.

**Comment by julianfez** [comment]
In the other homekit apps  it's exactly like this show the device but without capability of switch or anything ![](http://i.imgur.com/vIGJ5L7.jpg)

**Comment by pdlove** [comment]
This should be fixed with my latest commit.

**Comment by julianfez** [comment]
Looks like it's working the switches,  i have a few issues with the sensors 
Not showing all of them i have wemo and doesn't   detect motion 
I have 2 contacts sensors and only show 1 and the other only show temperature say contact no detected and it's working the battery as show in the pic
![](http://i.imgur.com/C9tSL3W.jpg)

Also i have lightsensor or illuminance from zwave and its not showing on the smartapp 
I have water sensor which Im going to test later and i let you know

**Comment by pdlove** [comment]
The water sensor won't show. Can you provide all of the console output when you start homebridge before the pin is displayed that starts with [SmartThings] and I'll be happy to extend it to all your sensor types.

**Comment by pdlove** [comment]
@julianfez Would you have some time today or tomorrow to get me that log entry so I can expand to your water sensor and light sensor?

**Comment by julianfez** [comment]
Sure let me now tomorrow any time

**Comment by pdlove** [comment]
@julianfez Can you provide all of the console output when you start homebridge before the pin is displayed that starts with [SmartThings] and I'll be happy to extend it to all your sensor types.
That should give me everything I need to support these devices.

**Comment by julianfez** [comment]
Thanks but i have another  i even delete the folder homebridge-SmartThings and reinstall again and i got this ![](http://i.imgur.com/Jaeq46x.jpg)

**Comment by julianfez** [comment]
I just delete the 443 port from the config.json SmartThings.js lib and it not showing any more

**Comment by pdlove** [comment]
Can you hit the config button from the smart app and verify that it should be "graph.api.smartthing.com"?
The most likely issue is that configuration is wrong. Either the App ID is different or it's using a different set of server.

**Comment by pdlove** [comment]
Is there still an issue?
