### ISSUE TITLE
Locks not responding or reporting accurate status

### ISSUE THREAD

**Issue by mishakim** [pdlove/homebridge-smartthings#31]
I'm not sure what locks are supposed to be able to do at this point, but they're not working for me. I was able to select my locks in the JSON app, and they appear in HomeKit, Siri is happy to tell me their state and try to control them, but the state is not accurate and the control commands do nothing. I don't see anything appear in the live log in the IDE or the log on my homebridge server when I try to interact with the locks.
They're Yale touchscreen deadbolts on Z-wave, if that matters

**Comment by allanak** [comment]
Same issue here with Schlage locks and my garage door. I get a "Device not found" error in the IDE for both after Siri asks me to unlock/provide fingerprint when I ask her to "unlock the front door" or "open the garage door."

> Sun, 14 Feb 2016 01:20:05 GMT EventedHTTPServer [192.168.1.145] HTTP request: /characteristics
Sun, 14 Feb 2016 01:20:05 GMT HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics
Sun, 14 Feb 2016 01:20:05 GMT Accessory [Homebridge] Processing characteristic set: [{"aid":40,"iid":9,"value":0}]
Sun, 14 Feb 2016 01:20:05 GMT Accessory [Homebridge] Setting Characteristic "Lock Target State" to value 0
Sun, 14 Feb 2016 01:20:06 GMT EventedHTTPServer [192.168.1.145] HTTP Repsonse is finished

**Comment by pdlove** [comment]
Which group are they in on the config screen?

**Comment by mishakim** [comment]
They're in "most things"

**Comment by pdlove** [comment]
See if this works for you now with Smart app 0.3.6.
I'm not sure if it will or not...

**Comment by allanak** [comment]
Nope, same outcome.

**Comment by mishakim** [comment]
My problem seems to be with Smartthings -- the JSON Complete API now shows up in the event log for my locks, but they don't respond to either homebridge or to direct SmartThings control, and the log is empty for the past two days. So I think the Homebridge side is OK, since it's making it to the log, and I need to troubleshoot why SmartThings itself has stopped working.

**Comment by pdlove** [comment]
@mishakim  So to clarify, it isn't working properly in your Smartthings app either?

**Comment by mishakim** [comment]
Correct - the SmartThings app is not able to control the locks at all, or report their status. It does show the incoming homebridge commands, but does not obey them. Haven't had a chance to troubleshoot it yet.

**Comment by mishakim** [comment]
Deleting and re-pairing one of the locks fixed it - it now shows accurate status in HomeKit apps, and the apps and Siri can lock/unlock. The other one still isn't working (I was hoping fixing one would do both), but I'll repeat the process eventually - we don't use that door in winter anyway.

**Comment by pdlove** [comment]
I'm going to mark this as a question since it's a smart things error. I'm also going to close it. If you feel you need help, just reopen it here and we'll all see if we can figure it out.
