### ISSUE TITLE
Control not working- log location?

### ISSUE THREAD

**Issue by coolcom** [pdlove/homebridge-smartthings#33]
Weird issue- when I ask siri to turn on a light, I can see the homekit getting the command (via app: Home), it toggles "on" but smartthings does not turn the light on. After 10 seconds, homekit reverts back to "off" on the app.

If i turn on the light via smartthings or manually, the homekit status (via app Home) reports the correct value (on).

So it seems to be able to get the values, but not send commands. Does that make sense? Are there any logs I can get to help?

**Comment by pdlove** [comment]
This makes some sense. I assume no errors are reported on the HomeKit log? Does this happen all the time for specific devices? If so, what kind of device?

**Comment by coolcom** [comment]
Where are HomeKit logs?

**Comment by jcharr1** [comment]
I'm having the same problem. It happens all the time with my wemo switches, zigbee light bulbs, and my Schlage Camelot z-wave door lock. I'm using v0.3.5 of the smart app and homebridge & homebridge-smartthings both seem to be up to date according to npm. It used to work fine for me up until I think the version that added the switches section in the smart app. 

This may be unrelated, but a couple days ago I added a good many bulbs and water leak sensors to ST and added them to the smart app. When I restarted homebridge I kept getting a rate limit error for a while. That error's gone now though.

**Comment by tonesto7** [comment]
I'm having the same issue.  The devices are reporting to homebridge they are just not responding to the control.

**Comment by tonesto7** [comment]
```
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:37:43 PM: error Device Not Found
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:37:43 PM: info Command Request
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:32:10 PM: error Device Not Found
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:32:09 PM: info Command Request
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:42 PM: error Device Not Found
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:42 PM: info Command Request
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:39 PM: error Device Not Found
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:39 PM: info Command Request
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:38 PM: error Device Not Found
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:38 PM: info Command Request
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:35 PM: error Device Not Found
fd2948bd-f0cb-4a7b-84cf-dde33722b7e9  10:28:35 PM: info Command Request
```

**Comment by rickybloomfield** [comment]
I'll also add that this is now happening to me as well (running the latest 0.3.5). It's definitely connected, but switches don't do anything.

**Comment by pdlove** [comment]
I just updated the Smartapp to 0.3.6. I made a very silly error.

**Comment by rickybloomfield** [comment]
That fixed it!

**Comment by jcharr1** [comment]
That fixed it for me, too. Thanks. :)

**Comment by tonesto7** [comment]
I'm not seeing any devices under Homebridge... 
I'm just seeing `[SmartThings] Error received type undefined - undefined` over and over
