### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by tannebil** [pdlove/homebridge-smartthings#34]
I installed the current version tonight and thought I'd pass along a few things I ran into along the way.

1) I got hung up on adding the repository to MySmartApps because there was no Settings option on the page. It turns out that I needed to add a new (empty) repository to my GitHub account named SmartThingsPublic. Once I did that, the Settings option appeared and I could complete the process. Maybe this could be made explicit in the README.md?

2) Running "homebridge" threw the following error:

Loaded plugin: homebridge-smartthings
Registering platform 'homebridge-smartthings.SmartThings'
---
Loaded config.json with 15 accessories and 2 platforms.
---
Loading 2 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:85
      throw new Error("The requested platform '" + name + "' has been registered multiple times. Please be more specific by writing one of: " + found.join(", "));
      ^

Error: The requested platform 'SmartThings' has been registered multiple times. Please be more specific by writing one of: homebridge-legacy-plugins.SmartThings, homebridge-smartthings.SmartThings
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:85:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:194:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

I'd been running the original smarthings plugin which apparently caused a conflict. I temporarily resolved it by updating config.json to point to homebridge-smartthings-SmartThings. I suspect I need to update homebridge to a newer version but my knowledge of npm is limited so I need to set aside some time to figure out if it's as simple as re-running npm install or if I need to remove packages first.

3) I've got my iPhone and my wife's iPhone configured as Presence Sensors. Although both phones were present, in HomeKit (Eve, Home) mine showed as "present" while her's showed "not present". I double-checked SmartThings and her's also showed as not present there so I went to her phone, ran Smartthings and enabled background processing. Her status turned to "present" in SmartThings but it stubbornly shows as "not present" in HomeKit. The polling_seconds option is set to 10. They looks identical in Device Results. Are they supposed to get polled?

4) In JSON Complete API, I have three device sections: 1) Most Devices, 2) Sensor Devices, and 3) All Switched. Some devices (the JASCO Lamp Module that came with the SmartThings hub for example) show uo in all three sections?  Should I select it in all three sections?

Overall, it's a great step forward from the older plug-in. Thanks!

**Comment by tonesto7** [comment]
I honestly think the new app selection is truly going to confuse people.  As much as I would like to keep things simple I really think we should split the inputs into more capabilities. This will prevent duplicate entries from being selected.

**Comment by pdlove** [comment]
It actually won't because you end up with a single item in 5 or 6 categories. There is duplicate protection as well. I have everything selected in all categories without problems.
@tennebil the problem is that you have the legacy plugin installed. Do not use smartthings in it and instead, reference the new platform as indicated in the read me.md file.

**Comment by tonesto7** [comment]
@pdlove 
I'm not seeing any devices in homebridge.  Just this `[SmartThings] Error received type undefined - undefined]' repeated over and over in the homebridge logs.

**Comment by pdlove** [comment]
@tonesto7 Make sure you api token and installation id is correct.

**Comment by tonesto7** [comment]
Thanks that was it.. The last update created a new id/token. 
When you get some time maybe put some form of logging into the homebridge plugin that indicates an auth failure.

**Comment by pdlove** [comment]
I think it was a result of the atomic state idiocy I did. You should be the only one affected since you were the only one with a Smartapp that actually properly used atomic state.
Everyone: Thank you so much for the patience on this!

**Comment by pdlove** [comment]
@tannebil Please confirm you are working now.

**Comment by tannebil** [comment]
I was working all along. My issues were all minor and temporary and the result of a missing piece of info (about needing to have a SmartThingsPublic repo in my GitHub account), user ignorance about the workings of platform name conflicts in homebridge, and the way HomeKit and/or homebridge and/or homebridge plugins and/or SmartThings app handle updating device states after a change.

I’m still confused about the reason devices show up multiple times in the SmartThings, SmartApps, JSON Complete API, config settings but my confusion doesn’t keep devices from showing up in HomeKit.

I see the occasional errors but nothing seems to be a critical issue. For example, in startup, I get for the tracking fob included in my SmartThings starter kit, a capabilities error:

[SmartThings] Device Added - Group sensor, Name Car Key, ID f8f05b43-af7b-49a4-a341-b2ded203fdb9
[SmartThings] Unknown Capabilities: ["Indicator","Signal Strength","Tone"]

While in the screen log, I’ve seen:

error at req:  { [Error: getaddrinfo EAI_AGAIN graph.api.smartthings.com:443]
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'graph.api.smartthings.com',
  host: 'graph.api.smartthings.com',
  port: '443' }

That error has only appeared once.

**Comment by pdlove** [comment]
I've added some verbiage on the Readme file about the necessity for the multiple groups and why it can't be avoided. 
Any idea what device has the Tone capability? That would be anything that beeps but not an alarm siren. If it is your "Car Key" device, I'm very interested in what that one is.

**Comment by tannebil** [comment]
The tracking fob is just a little dongle that can be attached to something to track that object is present or not. For example, if you attach it to the car keys or stick it in the glove box, it lets you know when the car leaves. You can send the dongle a “Beep” command in SmartThings which causes it to sound a tone so you can find it (if, for example, you constantly lose your car keys.

Here’s the current version (I have an older one)

https://www.smartthings.com/products/arrival-sensor

**Comment by pdlove** [comment]
Thanks. I didn't know they beeped. I'll need to get a couple.

**Comment by malixsys** [comment]
Great plugin @pdlove! What about "Signal Strength" can that be used somewhere?

**Comment by sh4fton** [comment]
I was having the same issue as Tonesto7, and noticed that sure enough my OAuth codes had changed. After trying to update my config.json and having no improvement, I clicked the buttons to Generate New Client ID and New Client Secret -- but now when I open the SmartApp in SmartThings and click the "Config" or "Device Results" buttons, they error out with an XML page saying invalid token... what am I missing?

**Comment by sh4fton** [comment]
Nevermind, I was able to resolve simply by removing the SmartApp and redoing it. All good again..
