### ISSUE TITLE
ghost device showing up in HomeBridge

### ISSUE THREAD

**Issue by mishakim** [pdlove/homebridge-smartthings#38]
this is a weird error, and totally understandable if it's too much of an edge case to fix.

I have a Aeon Labs z-wave plug-in outlet that quit working reliably, so I unplugged it for a couple of days. Prior to that, it was selected in the JSON Complete app and usable through Homebridge. While it was unplugged, it disappeared from SmartThings, and it didn't come back when I plugged it back in. I mainly use it on a schedule, which SmartThings can't handle right now, so I just excluded it using my other system (openHAB with a Z-stick) and re-included it there, where it's working fine. 

The problem is, the homebridge-smartthings plugin is still exporting it to HomeKit, where it is reporting its last known status and appears to be accepting on/off commands. I can't delete it from iDevices app, and it no longer appears in the list of devices under the JSON app to unselect it. 

Short of wiping out my JSON app and re-installing it, is there anyway to remove this ghost device?

**Comment by pdlove** [comment]
I don't think wiping out the JSON app will help. Do you see the device here: https://graph.api.smartthings.com/device/list

**Comment by mishakim** [comment]
No - that's what's weird. It disappeared from everything, except the homebridge device list coming out of the app. If I copy the hex address from that, and put it in the url, I can access the device's settings, but I can't delete it because it says it's in use by all the smart apps (this and various RM rules) that used to use it. The other rules had essentially the same issue - switch was listed in their actions, but not available to deselect when editing.  I was able to delete all the other rules, but it still says the old Json app (which I will delete) and this one are using it. That's why I was thinking I'd delete the Json app (maybe from ide too), then delete the phantom switch now that i know how to do that, and reinstall.

**Comment by pdlove** [comment]
Is it a zwave device? If so, you might try to "repair" the Z-Wave network on the hub and see if it drops off. If not, try doing a support ticket.

**Comment by mishakim** [comment]
It is z-wave, but repair didn't help. I tried deleting the Json smart app, and reinstalling, and that took care of it.

**Comment by mishakim** [comment]
I'll close this.  Unlikely to be reproduce able enough to fix.
