### ISSUE TITLE
Devices not being added

### ISSUE THREAD

**Issue by tonesto7** [pdlove/homebridge-smartthings#39]
I'm really having issues with the new update.  I'm only seeing some of my devices even if I select them in 2 or more lists.  I'm not seeing any errors on either logs

**Comment by tonesto7** [comment]
So I'm the only one having this issue?
I'm not even seeing the registering: Device.state messages since the last update either

**Comment by tonesto7** [comment]
@pdlove 
Shouldn't I be seeing constantly for every device state change in my logs:

`Registering Outside Switch.switch
477e440f-2003-43d2-90b3-4e63c2128331  2:52:53 PM: debug Registering Living Room Mini Light.switch
477e440f-2003-43d2-90b3-4e63c2128331  2:52:53 PM: debug Registering Living Room Fan.switch
477e440f-2003-43d2-90b3-4e63c2128331  2:52:54 PM: debug Registering Outside Garage Lights.switch
477e440f-2003-43d2-90b3-4e63c2128331  2:52:54 PM: debug Registering Outside Garage Lights.energy
477e440f-2003-43d2-90b3-4e63c2128331  2:52:53 PM: debug Registering Living Room Mini Light.level
477e440f-2003-43d2-90b3-4e63c2128331  2:52:53 PM: debug Registering Master Bedroom Light.switch`

**Comment by pdlove** [comment]
I would expect you to. I've been running a day with my subscription-based updates and haven't had any issues. I'll submit my code and re-publish the npm in another hour or so. I've like to see if it fixes your issue although I'm not confident that it will. The big thing I'd like to see is what the startup process shows. First, the Devices JSON reply and secondly the SmartThings items that log before the HomeKit pin is displayed.

**Comment by tonesto7** [comment]
It will run through once after updating the smart app

**Comment by tonesto7** [comment]
I appears to caused by efergy energy device.  Once I removed it the remaining devices loaded up.

**Comment by tonesto7** [comment]
How is the plugin handling unknown device commands/capabilities.

**Comment by pdlove** [comment]
It marks the device as unknown and moves on. unknown devices are not added as accessories. Do you know if it is the smart app or the plugin causing the issue?

**Comment by tonesto7** [comment]
It's hard to say which is the cause because it was showing up before the change to the new subscription based format. 
It is a custom device type with the following capabilities:
        capability "Energy Meter"
        capability "Power Meter"
        capability "Polling"
        capability "Refresh"
        capability "Actuator"

**Comment by pdlove** [comment]
That looks identical to what I'm seeing on my power monitor which is working beautifully.

**Comment by tonesto7** [comment]
There really needs to be some sort of logging.  This mystery crap is killing me.
I can see all of the devices listed in the syslog of homebridge but only 28 devices are being added to Homekit.  Of those 28 only like 10 are from SmartThings.  I need your help.

Here is my devices json from the app: https://dl.dropboxusercontent.com/s/63kayegmbxka3go/Untitled-1.json
Here is my syslog:https://dl.dropboxusercontent.com/s/6zv4d2zhkkd2nlf/Homebridge%20Logs.log

**Comment by tonesto7** [comment]
So I went in and removed persist folder and then checked all of the devices in all three smart app lists.  After rebooting everything was there.   So I tested some devices and restart the homebridge server.  this time half the devices are in homekit.  So i rebooted again all but 8 are available.  So something is not right with this new plugin setup.  I'm using 70+ devices with it.

**Comment by pdlove** [comment]
@tonesto7 looks like roughly 50 devices are recognized and added to home bridge, does that sound right? I'll have a chance tomorrow to look through the whole thing to see what exactly is going on with it.
The problem is, it sounds like not all of the devices being initialized are being visible in HomeKit?

**Comment by tonesto7** [comment]
It's close to 60+ devices, but your correct they are initializing but not pairing to homekit

**Comment by pdlove** [comment]
Ok. I'm going to get to know the process better tomorrow to determine what happens after homebridge initializes the devices so we can turn on some kind logging.

**Comment by tonesto7** [comment]
Sounds good... Thanks for all of your help

**Comment by tonesto7** [comment]
Any update on this?

**Comment by pdlove** [comment]
@tonesto7 Try this with the latest version please.

**Comment by Slepperpon** [comment]
Just today no devices except homebridge. Deleted files in homebridge and iPhone and tried starting over homebridge showed up but again that was it no devices. They all show up on Rpi but don't work or show up on phone.

**Comment by pdlove** [comment]
Can I get the accessories dump HomeKit gets from home bridge? you have to start the server with "homebridge -I" for insecure mode and then get it from your web browser. For example, my homebridge server is 192.168.0.4, so I go here for the dump: http://192.168.0.4:51826/accessories
Please email it to pdlovelace@gmail.com
It will help determine if the issue is in home bridge or HomeKit.
