### ISSUE TITLE
Thermostat just showing as temp sensor and contact (door) sensors just saying NO

### ISSUE THREAD

**Issue by KumarMudedla** [pdlove/homebridge-smartthings#4]
Hi, Bulbs are working as expected but 

**Thermostat** is just showing as temperature sensor not able to change the temperature and also not showing the mode, 
[SmartThings] Device Added - Group sensor, Name Thermostat, ID 0ea4cf4e-c439-4665-8b10-dd293cb598e7, JSON: {"name":"Thermostat","deviceid":"0ea4cf4e-c439-4665-8b10-dd293cb598e7","capabilities":{"Temperature Measurement":1,"Relative Humidity Measurement":1,"Battery":1,"Configuration":1,"Refresh":1,"Thermostat":1,"Sensor":1,"Actuator":1},"commands":{"configure":[],"refresh":[],"setHeatingSetpoint":["NUMBER"],"setCoolingSetpoint":["NUMBER"],"off":[],"heat":[],"emergencyHeat":[],"cool":[],"setThermostatMode":["ENUM"],"fanOn":[],"fanAuto":[],"fanCirculate":[],"setThermostatFanMode":["ENUM"],"auto":[],"setSchedule":["JSON_OBJECT"],"switchMode":[],"switchFanMode":[],"quickSetCool":[],"quickSetHeat":[]},"attributes":{"temperature":70,"humidity":53,"battery":98,"heatingSetpoint":69,"coolingSetpoint":75,"thermostatSetpoint":69,"thermostatMode":"off","thermostatFanMode":"fanAuto","thermostatOperatingState":"idle","schedule":null,"thermostatFanState":"idle"}}

**Door Contact Sensor** just says NO (no matter whether its opened or closed) it is showing the temp though.
[SmartThings] Device Added - Group sensor, Name Front door, ID 29ad2cfd-c374-4bb0-b2b9-26bf3849c216, JSON: {"name":"Front door","deviceid":"29ad2cfd-c374-4bb0-b2b9-26bf3849c216","capabilities":{"Temperature Measurement":1,"Battery":1,"Contact Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":60,"battery":88,"contact":"closed"}}

[SmartThings] Unknown Capabilities: ["Relative Humidity Measurement","Thermostat"]
[SmartThings] Initializing platform accessory 'Bed room Bed Lamp'...
[SmartThings] Initializing platform accessory 'Dining Bulb 1'...
[SmartThings] Initializing platform accessory 'Front door'...
[SmartThings] Initializing platform accessory 'Hall way Bulb'...
[SmartThings] Initializing platform accessory 'Kitchen Bulb1'...
[SmartThings] Initializing platform accessory 'Living Bulb Back Left'...
[SmartThings] Initializing platform accessory 'Living Bulb Back Right'...
[SmartThings] Initializing platform accessory 'Thermostat'...

**Comment by pdlove** [comment]
Thanks for the detailed information. I'll use your thermostat data here along with my own to make that work out. I'll also double check the contact sensor logic.
I should be able to upload the fixes tomorrow night.

**Comment by KumarMudedla** [comment]
Thanks pdlove, I am using [2gig CT100](http://www.amazon.com/gp/product/B008CQ4V3Q?psc=1&redirect=true&ref_=ox_sc_sfl_title_2&smid=ATVPDKIKX0DER) Thermostat it has 4 modes (Cool, Heat, Auto, Off) till now I am using below Smartthings plugin 

[arcreative/homebridge-smartthings --# 4](https://github.com/arcreative/homebridge-smartthings/blob/fahrenheit/index.js)

the only thing not working is get and set the temperature while it is in Auto mode, we have calculate the nearest temperature set that value. (we can simply assume High=CoolingSetpoint and Low=Heatingsetpoint) and then calculate which one siri need to set for example there are doing the same for Nest 

[Homebridge-nest](https://github.com/KraigM/homebridge-nest/blob/master/index.js) i tried to implement but I am not so good at js

NestThermostatAccessory.prototype.getTargetTemperature = function () {
	switch (this.getTargetHeatingCooling()) {
		case Characteristic.CurrentHeatingCoolingState.HEAT | Characteristic.CurrentHeatingCoolingState.COOL:
			// Choose closest target as single target
			var high = this.currentData.target_temperature_high;
			var low = this.currentData.target_temperature_low;
			var cur = this.currentData.current_temperature;
			return Math.abs(high - cur) < Math.abs(cur - low) ? high : low;
		default:
			return this.currentData.target_temperature;
	}
};

**Comment by pdlove** [comment]
This is because I don't have the Thermostat Accessory in there yet. It is reporting as a Temperature Sensor at the moment.

I added my thermostat last night to SmartThings so I can get everything finished up to do the update tonight to support thermostats properly.

**Comment by KumarMudedla** [comment]
thanks for your work, it is showing the target temperature as mid point (coolingsetpoin+heatingsetpoint/2) 
for example 71 is the current temp and my thermostat coolsetpoint=75 and heatsetpoint=69 and eve app showing the temp as 72

I copied the logic from [Homebridge-Nest  (look at lines 373 to 384)](https://github.com/KraigM/homebridge-nest/blob/master/index.js) to the your accessories js for the get method and then it was showing the temp correctly as 69

and also I am not able to set the temperature when i set temp to 71 and as soon as i refresh the app it is going to back. so its actually setting the value.

**Comment by pdlove** [comment]
Thanks. I was considering doing it the way it is done in Nest but didn't want it to be too confusing to the end user. If you set it from HomeKit, does it update with the value you set 10 seconds later?
On switches, I put in the assumption that the command would execute in order to tell HomeKit the new value was correct before the update came back from Smartthings. I neglected to do that with the Thermostat settings. I'll hook up my old z-wave thermostat from before I switched to Ecobee and see how it responds tomorrow night.

**Comment by KumarMudedla** [comment]
No, its not setting the value at all even after 10 sec or may be the value is not properly configured C or F conversation (above the min & mac range handled by homekit) as today my homebridge not responding many times and I got to redo the whole thing with new name (I heard that if we give a value above the range then apple will block list that bridge)

**Comment by KumarMudedla** [comment]
I witnessed again it was good until I set the temp via Eve( or Siri) and then the Homebridge becomes unreachable, restarting the Homebridge not fixing the issue, (I got to redo the whole thing again) , 

I am assuming when i set temp to 70, it is getting converted to (70*1.8)+32=158 (that is above the max range) so apple may be block listing the bridge completely. 

below has the correct logic for the C to F (or F to C) conversion but the only issue is setting\getting temp in AUTO mode is not implemented in this
https://github.com/arcreative/homebridge-smartthings/blob/fahrenheit/index.js

**Comment by pdlove** [comment]
HomeKit works always in Celsius even when the app displays Fahrenheit. It looks like one doing it exactly the same as the other plugin. I'll work with this specifically tonight. In auto mode, should it set both temperatures to the same or only adjust the temperature closest to current?

**Comment by KumarMudedla** [comment]
thanks, my homebridge keep going unreachable, so probably I will play with this on my ipad with test apple account. From my thermostat unit we can only set one temperature (it doesn't have cooling and heatingsetpoints) but from the ST app we have both heating and cooling set points, in Auto mode i guess ST will manage the setup point depending on the current temperature.

**Comment by pdlove** [comment]
I'm not able to cause the issue with it going un reachable as my thermostat rejects the temperature I'm giving it. I do see the bug. I manipulate the temperature and then pass the unadjusted Celsius temp. I'll get it corrected and also fix some of my other logic flaws tomorrow.

**Comment by KumarMudedla** [comment]
thanks, I guess the "unreachable" issue is looks like not related to this at all, many other are having same issue on RaspberryPI, So I moved my Rpi to my direct router (it used to be on different switch) and it is looking stable from yesterday evening.
