### ISSUE TITLE
Missing capabilities

### ISSUE THREAD

**Issue by rickybloomfield** [pdlove/homebridge-smartthings#42]
The following are listed on startup. Not sure if it matters. Things seem to be working well and I'm not sure there's a need to add these.

[SmartThings] Unknown Capabilities: ["Thermostat Cooling Setpoint","Thermostat Mode","Thermostat Fan Mode","Thermostat Operating State","Thermostat Heating Setpoint","Thermostat Setpoint","Indicator"]

**Comment by pdlove** [comment]
I'll add them as "Known Capabilities". What model of device is reporting these?
I may need to add a check "If a thermostat wasn't detected, look for one of these."

**Comment by rickybloomfield** [comment]
It's an ecobee3, but there's not native ecobee3 integration in SmartThings, so the following library is used, if that makes a difference: https://github.com/StrykerSKS/SmartThingsPublic/tree/StrykerSKS-Ecobee3/smartapps/smartthings/ecobee-connect.src

**Comment by pdlove** [comment]
I see. I use a different set for the ecobee3 that was a pay item: https://github.com/yracine/device-type.myecobee
It seems to work really well, but I may look at that one as well.
I'm going to add the other Thermostat capabilities as known without really doing anything else. I'll also check on the Indicator capability and see what it needs.
Thanks for the information!

**Comment by rickybloomfield** [comment]
I used to use that one as well, but this new one sprung up as a response to the other one becoming closed source. This one has worked much better for me and has a cleaner and more functional SmartApp with less bugs. It's actively being developed. Thanks!
