### ISSUE TITLE
Duplicate instances of SmartApp and no "Remove" button

### ISSUE THREAD

**Issue by rickybloomfield** [pdlove/homebridge-smartthings#5]
Hi, I installed the SmartApp and after installing I'm seeing many instances of it (17 by my count. I thought this may correlate with the number of devices I added, but that was 20, so they don't match). You can see this in the attached screenshot. Also, there is no way to remove any of these instances. When I tap on it, there is no "Remove" button like all of the other SmartApps I have installed (second screenshot).

Many instances of "JSON Complete API"
![img_4100](https://cloud.githubusercontent.com/assets/868473/12749540/5dc657ae-c97f-11e5-92d8-1686de4a1557.jpg)

No "Remove" button:
![img_4101](https://cloud.githubusercontent.com/assets/868473/12749563/7a84493c-c97f-11e5-828e-e349cf1ac3fc.jpg)

**Comment by pdlove** [comment]
I've update the smartapp to show the remove button.
You can also remove them fairly quickly here: https://graph.api.smartthings.com/location/list
Login and goto "List SmartApps" then hit edit. It will let you remove all of them rapidly.

**Comment by rickybloomfield** [comment]
Great, thanks. Just removed them.

**Comment by rickybloomfield** [comment]
I just realized that the old JSON API app didn't have a remove button, either - I never tried to remove it. That explains things. Will be nice to get that in there. It's already better than the old one!

**Comment by pdlove** [comment]
@rickybloomfield I have had one device not show up int the "All Devices" list. It was custom device that exposed my Ecobee remote sensors. I simply added the "Refresh" characteristic to it the custom device and it works now.
