### ISSUE TITLE
Thermostat - Current Temperature not being refreshed

### ISSUE THREAD

**Issue by alisdairjsmyth** [pdlove/homebridge-smartthings#54]
Same issue as #35. The current temperature is not being updated as part of the polling process. I am presently watching the temperature as reported in Smartthings decline, and the temperature in the HomeKit App remain constant.

`homebridge.err` contains the following entries (`homebridge.log` only has initialisation messages):
`Sun, 06 Mar 2016 10:13:05 GMT Accessory [bridge] Getting value for Characteristic "Current Temperature"`
`Sun, 06 Mar 2016 10:13:05 GMT Accessory [bridge] Got Characteristic "Current Temperature" value: 24.7`
`Sun, 06 Mar 2016 10:25:25 GMT Accessory [bridge] Getting value for Characteristic "Current Temperature"`
`Sun, 06 Mar 2016 10:25:25 GMT Accessory [bridge] Got Characteristic "Current Temperature" value: 24.7`
`Sun, 06 Mar 2016 10:25:38 GMT Accessory [bridge] Getting value for Characteristic "Current Temperature"`
`Sun, 06 Mar 2016 10:25:38 GMT Accessory [bridge] Got Characteristic "Current Temperature" value: 24.7`
`Sun, 06 Mar 2016 10:25:44 GMT Accessory [bridge] Getting value for Characteristic "Current Temperature"`
`Sun, 06 Mar 2016 10:25:44 GMT Accessory [bridge] Got Characteristic "Current Temperature" value: 24.7`

During this same window of time, according to the Smartthings Event Log, the temperature declined from 24.4 to 24.3, and it hadn't been 24.7 for at least 90 minutes.

Environment:
- Homebridge-Smartthings: 0.4.3
- Homebridge-Smartthings SmartApp: 0.4.1
- HomeKit App: Eve
- `polling_seconds`: 60

**Comment by alisdairjsmyth** [comment]
Using the SmartApp and "view accessories JSON" under "Device Results" - the JSON payload includes the name-value pair `"temperature": 23.9` under `attributes`

Eve (and Siri) continue to report 24.7.

**Comment by alisdairjsmyth** [comment]
Upgraded to current versions of Homebridge-Smartthings components:
- Homebridge-Smartthings: 0.4.4
- Homebridge-Smartthings SmartApp: 0.4.1 (though README.md states current version is 0.4.3)

State continues to not be refreshed

**Comment by pdlove** [comment]
I was able to iron out one major issue last night an just released that as 0.4.6.
The bug only really affected people using Celsius instead of what everyone else uses (Fahrenheit). Yes, I am joking as I realize that most of the world uses Celsius.
The bug also affected brightness and possibly door state reporting.

**Comment by alisdairjsmyth** [comment]
I have updated to implementation as follows:
- Homebridge: 0.3.2
- Home-Smartthings: 0.4.6
- Homebridge-Smartthings SmartApp: 0.4.1

... will provide an update on whether state, in this case Temperature in Celsius is being updated.

**Comment by alisdairjsmyth** [comment]
@pdlove - I am still experiencing the original issue

**Comment by pdlove** [comment]
Your temperature isn't being refreshed? Is everything else working just fine with it except for that?

**Comment by alisdairjsmyth** [comment]
My thermostat is the only device connected to homebridge via this plugin. I
am setting state changes through other plugins (homebridge-lifx-lan and
homebridge-sonos).

The correct temperature is visible through SmartThings App exposing the API
for this plugin.

**Comment by alisdairjsmyth** [comment]
Stop the press ... it seems to have started refreshing. Not sure what
changed. I will monitor but at this stage it appears to be working as
expected.

**Comment by alisdairjsmyth** [comment]
Stop the press ... updates have started flowing through. Not sure why it has started working as I haven't changed anything. Will monitor for an hour or so and will close if I continue to see updates.

**Comment by alisdairjsmyth** [comment]
Closing
