### ISSUE TITLE
Cant Add Momentary switches not appearing

### ISSUE THREAD

**Issue by humac** [pdlove/homebridge-smartthings#6]
i just got this working and I noticed my momentary switches are not showing up in the smart app. So I can't select them.

**Comment by pdlove** [comment]
Can you get me a screenshot of a momentary switch in the smart app? I need to try to interpret what "capabilities" are on it.

**Comment by humac** [comment]
what do you mean by screenshot in the smart app?  your smart app doesn't see the momentary switch.

However in the IDE the device handler for a momentary switch i'm using has the following in the capabilities section:

metadata {
	definition (name: "Momentary Button Tile", namespace: "smartthings", author: "SmartThings") {
		capability "Actuator"
		capability "Switch"
		capability "Momentary"
		capability "Sensor"
	}

**Comment by humac** [comment]
![image](https://cloud.githubusercontent.com/assets/9813864/12864726/2ba3ce00-cc63-11e5-8c2e-2e7d93b12af8.png)

**Comment by humac** [comment]
Also from my output log of homebridge i see the following, unknown capabilities.

[SmartThings] Unknown Capabilities: ["Power Meter","Indicator","Relay Switch","Water Sensor","Valve"]

**Comment by pdlove** [comment]
Please try this with the latest release. Also, can I get a snip of all of the SmartThings line before the "Unknown Capabilities" line?

**Comment by humac** [comment]
Just tried this.  In the new app whats the difference between "most devices" and "sensor devices"

This was from before I tried your new code:
[SmartThings] Device Added - Group sensor, Name 1st Floor Back Motion, ID <ID>, JSON: {"name":"1st Floor Back Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":22,"battery":77,"motion":"active"}}
[SmartThings] Device Added - Group sensor, Name 1st Floor Front Motion, ID <ID>, JSON: {"name":"1st Floor Front Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":20,"battery":77,"motion":"inactive"}}
[SmartThings] Device Added - Group sensor, Name Basement Studio Motion, ID <ID>, JSON: {"name":"Basement Studio Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":14,"battery":66,"motion":"inactive"}}
[SmartThings] Device Added - Group switch, Name Christmas Tree, ID <ID>, JSON: {"name":"Christmas Tree","deviceid":"<ID>","capabilities":{"Switch":1,"Configuration":1,"Refresh":1,"Power Meter":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[]},"attributes":{"switch":"off","power":0,"heartbeat":"alive"}}
[SmartThings] Device Added - Group lights, Name Family Room Lamp, ID <ID>, JSON: {"name":"Family Room Lamp","deviceid":"<ID>","capabilities":{"Switch":1,"Switch Level":1,"Refresh":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"setLevel":["NUMBER","NUMBER"],"refresh":[]},"attributes":{"switch":"off","level":100}}
[SmartThings] Device Added - Group switch, Name Fire Place, ID <ID>, JSON: {"name":"Fire Place","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"off","indicatorStatus":"never"}}
[SmartThings] Device Added - Group sensor, Name Front Door, ID <ID>, JSON: {"name":"Front Door","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Contact Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":18,"battery":66,"contact":"closed"}}
[SmartThings] Device Added - Group garage_doors, Name Garage Door, ID <ID> JSON: {"name":"Garage Door","deviceid":"<ID>","capabilities":{"Switch":1,"Contact Sensor":1,"Polling":1,"Refresh":1,"Momentary":1,"Sensor":1,"Actuator":1,"Relay Switch":1,"Door Control":1,"Garage Door Control":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"push":[],"open":[],"close":[]},"attributes":{"switch":"off","contact":"closed","door":"closed"}}
[SmartThings] Device Added - Group lights, Name Garage Light, ID <ID>, JSON: {"name":"Garage Light","deviceid":"<ID>","capabilities":{"Switch":1,"Switch Level":1,"Refresh":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"setLevel":["NUMBER","NUMBER"],"refresh":[]},"attributes":{"switch":"off","level":100}}
[SmartThings] Device Added - Group sensor, Name Guest Bedroom Door, ID <ID>, JSON: {"name":"Guest Bedroom Door","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Contact Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":19,"battery":66,"contact":"closed"}}
[SmartThings] Device Added - Group switch, Name Guest Bedroom Heater, ID <ID>, JSON: {"name":"Guest Bedroom Heater","deviceid":"<ID>","capabilities":{"Switch":1,"Configuration":1,"Refresh":1,"Power Meter":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[]},"attributes":{"switch":"on","power":0,"heartbeat":"alive"}}
[SmartThings] Device Added - Group sensor, Name Guest Bedroom Motion, ID <ID>, JSON: {"name":"Guest Bedroom Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":14.71,"battery":66,"motion":"inactive"}}
[SmartThings] Device Added - Group switch, Name Holiday Lights, ID <ID>, JSON: {"name":"Holiday Lights","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"off","indicatorStatus":null}}
[SmartThings] Device Added - Group switch, Name Hot Water Kettle, ID <ID>, JSON: {"name":"Hot Water Kettle","deviceid":"<ID>","capabilities":{"Switch":1,"Configuration":1,"Refresh":1,"Power Meter":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[]},"attributes":{"switch":"on","power":0,"heartbeat":"alive"}}
[SmartThings] Device Added - Group lights, Name Huy's Bedside Lamp, ID <ID>, JSON: {"name":"Huy's Bedside Lamp","deviceid":"<ID>","capabilities":{"Switch":1,"Switch Level":1,"Refresh":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"setLevel":["NUMBER","NUMBER"],"refresh":[]},"attributes":{"switch":"off","level":100}}
[SmartThings] Device Added - Group sensor, Name Interior Garage Door, ID <ID>, JSON: {"name":"Interior Garage Door","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Contact Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":21,"battery":66,"contact":"closed"}}
[SmartThings] Device Added - Group switch, Name Jasmine's Room Heater, ID <ID>, JSON: {"name":"Jasmine's Room Heater","deviceid":"<ID>","capabilities":{"Switch":1,"Configuration":1,"Refresh":1,"Power Meter":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[]},"attributes":{"switch":"off","power":0,"heartbeat":"alive"}}
[SmartThings] Device Added - Group sensor, Name Jasmine's Room Motion, ID <ID>, JSON: {"name":"Jasmine's Room Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":20,"battery":77,"motion":"inactive"}}
[SmartThings] Device Added - Group sensor, Name Kid's Bathroom Moisture, ID <ID>, JSON: {"name":"Kid's Bathroom Moisture","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Water Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":22,"battery":77,"water":"dry"}}
[SmartThings] Device Added - Group sensor, Name Kitchen Moisture, ID <ID>, JSON: {"name":"Kitchen Moisture","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Water Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":21,"battery":77,"water":"dry"}}
[SmartThings] Device Added - Group sensor, Name Laundry Room Moisture, ID <ID>, JSON: {"name":"Laundry Room Moisture","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Water Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":22,"battery":77,"water":"dry"}}
[SmartThings] Device Added - Group switch, Name Main Water Valve, ID <ID>, JSON: {"name":"Main Water Valve","deviceid":"<ID>","capabilities":{"Switch":1,"Battery":1,"Configuration":1,"Refresh":1,"Valve":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[],"open":[],"close":[]},"attributes":{"switch":"on","battery":null,"contact":null}}
[SmartThings] Device Added - Group sensor, Name Master Bathroom Moisture, ID <ID>, JSON: {"name":"Master Bathroom Moisture","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Water Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":20,"battery":77,"water":"dry"}}
[SmartThings] Device Added - Group sensor, Name Master Bedroom Motion, ID <ID>, JSON: {"name":"Master Bedroom Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":19,"battery":77,"motion":"inactive"}}
[SmartThings] Device Added - Group lights, Name Michelle's Bedside Lamp, ID <ID>, JSON: {"name":"Michelle's Bedside Lamp","deviceid":"<ID>","capabilities":{"Switch":1,"Switch Level":1,"Refresh":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"setLevel":["NUMBER","NUMBER"],"refresh":[]},"attributes":{"switch":"off","level":100}}
[SmartThings] Device Added - Group switch, Name Nespresso, ID <ID>, JSON: {"name":"Nespresso","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"on","indicatorStatus":null}}
[SmartThings] Device Added - Group switch, Name Outdoor Back Light, ID <ID>, JSON: {"name":"Outdoor Back Light","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"off","indicatorStatus":null}}
[SmartThings] Device Added - Group switch, Name Outdoor Front Light, ID <ID>, JSON: {"name":"Outdoor Front Light","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"off","indicatorStatus":null}}
[SmartThings] Device Added - Group switch, Name Outdoor Patio Lights, ID <ID>, JSON: {"name":"Outdoor Patio Lights","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"off","indicatorStatus":null}}
[SmartThings] Device Added - Group sensor, Name Patio Door, ID <ID>, JSON: {"name":"Patio Door","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Contact Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":18,"battery":66,"contact":"closed"}}
[SmartThings] Device Added - Group sensor, Name Powder Room Moisture, ID <ID>, JSON: {"name":"Powder Room Moisture","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Water Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":21,"battery":77,"water":"dry"}}
[SmartThings] Device Added - Group lights, Name Upper Hallway Light, ID <ID>, JSON: {"name":"Upper Hallway Light","deviceid":"<ID>","capabilities":{"Switch":1,"Polling":1,"Switch Level":1,"Refresh":1,"Indicator":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"poll":[],"setLevel":["NUMBER","NUMBER"],"refresh":[],"indicatorWhenOn":[],"indicatorWhenOff":[],"indicatorNever":[]},"attributes":{"switch":"off","level":50,"indicatorStatus":null}}
[SmartThings] Device Added - Group switch, Name Van's Room Heater, ID <ID>, JSON: {"name":"Van's Room Heater","deviceid":"<ID>","capabilities":{"Switch":1,"Configuration":1,"Refresh":1,"Power Meter":1,"Sensor":1,"Actuator":1},"commands":{"on":[],"off":[],"configure":[],"refresh":[]},"attributes":{"switch":"off","power":0,"heartbeat":"alive"}}
[SmartThings] Device Added - Group sensor, Name Van's Room Motion, ID <ID>, JSON: {"name":"Van's Room Motion","deviceid":"<ID>","capabilities":{"Temperature Measurement":1,"Battery":1,"Motion Sensor":1,"Configuration":1,"Refresh":1},"commands":{"configure":[],"refresh":[],"enrollResponse":[]},"attributes":{"temperature":19.25,"battery":77,"motion":"inactive"}}
[SmartThings] Unknown Capabilities: ["Power Meter","Indicator","Relay Switch","Water Sensor","Valve"]

**Comment by humac** [comment]
Virtual Momentary button appears but doesn't seem do anything.  Though in ST the virtual momentary switch works fine

**Comment by pdlove** [comment]
Sensor Devices are all of those that don't have the refresh capability. I'll sift through the information you provided.

**Comment by pdlove** [comment]
Momentary switches are a problem because of the polling. I'm flagging this for now as wont fix, but please don't close it because I need to re-evaluate it after I get the subscription-based updates working.

**Comment by humac** [comment]
Just tested my momentary switches and they all behave as expected
