### ISSUE TITLE
Incorrect Hue Output?

### ISSUE THREAD

**Issue by adamkempenich** [pdlove/homebridge-smartthings#60]
I've noticed that SmartThings was having an issue with Hues over 100 being sent to one of my devices from Homebridge-Smartthings and investigated it. [SmartThings documentation ](http://docs.smartthings.com/en/latest/capabilities-reference.html?highlight=color#color-control) says this value should be between 0-100%, but it is being sent as a value from 0-360. 

A personal test dividing the output  of a hue by 3.6 to convert the value to percentage proved successful.

Any chance this could be fixed for the public build?

**Comment by pdlove** [comment]
Will do. I'm testing an upgraded Plugin using the Plugin version 2 framework and should be posting it tomorrow. I'll update the hue issue at the same time. Thanks for looking into it. I've always wondered why Siri seemed to not know her colors.

**Comment by pdlove** [comment]
I have fixed this in the latest build. Thanks for finding it!
