### ISSUE TITLE
Am I missing SmartApp 4.3?

### ISSUE THREAD

**Issue by clayton-anderson** [pdlove/homebridge-smartthings#62]
Hi,

Things seem to be far more stable (NPM 0.4.6 vs 0.4.3) in my setup with Smartthings and Homebridge running on my Mac Mini server - thanks for all the hard work - it dropped each time I left and returned to the wifi network before, but seems to work better now. 

I see that the readme states there is a 0.4.3 version of the app - but I'm only seeing 0.4.1 - am I not finding it?

Thanks!

Clayton

**Comment by pdlove** [comment]
@clayton-anderson The readme was incorrect. I thought I was going to have to update the app and increased the version but never reduced it again.
Make sure you update smartthings-homebridge to 0.4.6. It fixes a bug in brightness changes that can crash HomeKit.

**Comment by clayton-anderson** [comment]
Thanks, will do! Great work and thanks for the quick reply!
