### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by rickybloomfield** [pdlove/homebridge-smartthings#63]
I've recently starting getting this error after reinstalling homebridge. I've triple-checked my config.json to make sure it's correct (along with the URL). Any thoughts as to the cause? Perhaps related to the current SmartThings outages?

![invalid response](https://cloud.githubusercontent.com/assets/868473/13973696/f1410768-f07b-11e5-8fa3-1a602e0a632f.png)

**Comment by pdlove** [comment]
This error is a dns resolution error. Fortunately it should not cause problems. The default setup does 1 request a second. So if you only have one over a time then it isn't too bad. I'll add a time stamp to these errors and see if I can find out why it isn't just using a cached response like I would expect. Most of the errors I see from people are dns related. I use google's DNS servers and don't see this issue so I assume it is a dns rate limiter somewhere.
