### ISSUE TITLE
Devices not added

### ISSUE THREAD

**Issue by jeffgloe** [pdlove/homebridge-smartthings#64]
I have followed your instructions with the exception of the config.json file.  My file is as follows:
{
"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},	
"description": "JSON API",
	"platforms": [{
		"platform": "SmartThings",
		"name": "SmartThings",
		"app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
		"app_id": "xxx",
		"access_token": "xxx"
			}
]
}

I have a ceiling fan switch, multiple dimmers, locks and a thermostat.  What should I try to resolve this?

**Comment by pdlove** [comment]
Please provide what you see when you launch homebridge. Everything befor the pin is displayed.

**Comment by rvsiqueira** [comment]
Rafaels-Mac-mini:homebridge rafaelsiqueira$ homebridge
[7/2/2016, 10:34:46 PM] Loaded plugin: homebridge-smartthings
[7/2/2016, 10:34:46 PM] Registering platform 'homebridge-smartthings.SmartThings'
[7/2/2016, 10:34:46 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

I have the same problem. For me any device doesn't load. I tried to copy the config.json in both folder homebridge and homebridge-smartthings

**Comment by jeffgloe** [comment]
I was able to get this working by changing the platform to "homebridge-smartthings.SmartThings"
