### ISSUE TITLE
Devices not showing up for me

### ISSUE THREAD

**Issue by flynhawaiian** [pdlove/homebridge-smartthings#65]
So for some reason none of the devices show up on home bridge.

It shows:
[4/11/2016, 1:18:13 PM] Loaded plugin: homebridge-smartthings
[4/11/2016, 1:18:13 PM] Registering platform 'homebridge-smartthings.SmartThings'
[4/11/2016, 1:18:13 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

**Comment by flynhawaiian** [comment]
got it working now!

**Comment by bcsolomon** [comment]
I am having the same problem. How did you fix it?

**Comment by flynhawaiian** [comment]
Now I cannot remember what I did to fix this.  Any thoughts?

**Comment by flynhawaiian** [comment]
Figured it out needed to just put the config.json in the /.homebridge folder :)
