### ISSUE TITLE
SmartSense Open/Cose Sensor aren't updating state and temp

### ISSUE THREAD

**Issue by humac** [pdlove/homebridge-smartthings#7]
I have smart sense open/close sensors and they pair as open  when the door is closed, and they don't update afterwards.  Also the temp is always 0.0 degrees.

**Comment by pdlove** [comment]
I'll upload a fix for state tomorrow. Is your temperature in Celsius? Mine was working this morning but I think it will be messed up in it's current state if the temp isn't being reported in Fahrenheit.

**Comment by humac** [comment]
Yes mines in Celsius, it seems all my things that report temp are showing a temp other than 0.0

**Comment by humac** [comment]
Contact updates but takes about 8 secs avg. temp still reading as 0.0

**Comment by pdlove** [comment]
This is due to the 10 second polling frequency. I'm making this user configurable and looking into how to have updates pushed from the api using subscriptions. Also on #9,

**Comment by tonesto7** [comment]
I'm seeing the temp on my ST Multi's but the contact state is always open.

**Comment by pdlove** [comment]
I verified that my contact state is changing properly. Please verify with the latest version.

**Comment by WPrinsloo** [comment]
Mine was also not showing temperature.  I changed my temperature scale in SmartThings to F and now it shows up but converted correctly in Celsius!

**Comment by pdlove** [comment]
Where do I change my temperature scale? I'll flip mine to C and work on it.

**Comment by WPrinsloo** [comment]
I also struggled to find it - don't like the new SmartThings app.  I changed it in graph.api.smartthings.com under my locations.

**Comment by pdlove** [comment]
I'm closing this as I believe it to be corrected.
