### ISSUE TITLE
Using the SmartApp for other things

### ISSUE THREAD

**Issue by edasque** [pdlove/homebridge-smartthings#71]
Hi,

am I right to think the smart app is a better version of the existing JSON API and could be used to write application that need to connect to Smartthings? Do you plan to document the API or what it adds to the existing one?

Regards,

Erik

**Comment by pdlove** [comment]
In reworking the smartapp, I took a lot of care to keep it general to useful in more apps.
In fact, once things lighten up a bit at work, I plan to write a data logger that uses the Json smartapp. I got a zwave energy monitor and suddenly realized that smartthings doesn't record the data in any easily usable way.
I have not given much thought to documenting the usage of it, but I can do so as I work with the new tool.

**Comment by edasque** [comment]
I haven't found a good tutorial that shows how to use a REST or other HTTP based API to communicate with my hub through the SmartThings API, it looks like this could help do that, right? I am not trying to build a full app on the Smartthings app but communicate with my devices from an app that isn't mobile.

**Comment by edasque** [comment]
@pdlove can you please give me an example of a REST call that would trigger an event like open a door or a garage door for example? And maybe something to get an open/close status?

**Comment by pdlove** [comment]
Check out the new readme file: https://github.com/pdlove/homebridge-smartthings/blob/master/smartapps/pdlove/json-complete-api.src/readme.md

**Comment by edasque** [comment]
Very very helpful, thank you.
