### ISSUE TITLE
Homebridge Smartthings Has Been Running Fine But Now Seeing Errors

### ISSUE THREAD

**Issue by Wildcat1** [pdlove/homebridge-smartthings#74]
Per the title this has been running very well with no errors since the last fix. However recently (as in the past week or two) I have started to notice some errors. Today for example I am seeing the following:

[homebridge-smartthings.SmartThings] Invalid Response from API call

As well as:

Verify Fail
Layer Decrypt fail!

I am also seeing devices random fall out of Homekit again. Wondering if anyone else is seeing these and if @pdlove you can lend us your expertise ?

Thanks so much as always

**Comment by Wildcat1** [comment]
@pdlove I am still seeing this issue and now am seeing other errors that I am copying below for reference. Not sure if this is relating to changes Apple is making on the backend for HomeKit and iOS 10 / MacOS Sierra or for additions in the way in which Apple TV can now interface HomeKit and this is what has changed back end handling but know that up until recently this has been running phenomenally well thanks to your last fix. Any ideas ?

Thanks

[6/25/2016, 10:16:03 AM] Current temperature for Nest Thermostat is: 74 F
Verify Fail
Layer Decrypt fail!
[6/25/2016, 10:35:20 AM] Current heating for Nest Thermostat is: Cooling
Verify Fail
Layer Decrypt fail!
[6/25/2016, 11:33:54 AM] Current temperature for Nest Thermostat is: 74 F
[6/25/2016, 11:33:54 AM] Current heating for Nest Thermostat is: Off
Verify Fail
Layer Decrypt fail!
Verify Fail
Layer Decrypt fail!
undefined:1
{"characteristics":[{"aid":2,"iid":17,"ev":true},{"aid":2,"iid":20,"ev":true},{"aid":3,"iid":17,"ev":true},

**_Then lists a bunch of other characteristics until finally displaying:_**
                                                                            
SyntaxError: Unexpected token

**Comment by pdlove** [comment]
I'm closing this due to the drastic changes made. Please re-open if you are having problems after updating.
