### ISSUE TITLE
State does not change in homekit

### ISSUE THREAD

**Issue by garywkfung** [pdlove/homebridge-smartthings#77]
I went through all the installation steps and managed to get the motion sensor and power outlet to appear as devices in homekit. 

But the state doesn't ever change. I've double checked in the smartthings app and the state is changed there, just not homekit. Why?

**Comment by gl-lamhnguyen** [comment]
Same, I have virtual devices created from device handler, and they aren't synced correctly with the actual status in ST

**Comment by pdlove** [comment]
Do they update hourly in HomeKit or not at all? By default, the smartapp registers to receive updates. Some custom work could cause an issue with this that would need polling to work. By default the full device polling occurs hourly.

**Comment by mshollack** [comment]
Any answers to this? My devices don't refresh or show correct device state in the home app. It does within the smart things iOS app. Lights, switches, garage doors. I'm using aeon labs micro switches. Some lights will refresh, others don't. Seems to be if I interact with the device from the home app first.

**Comment by mshollack** [comment]
I believe the issue is corrected. I did not read your notes to remove the Polling_Seconds variable from the config.json file within the home bridge directory.  Once I did so, then my devices started to sync to the correct state within a second or less.
