### ISSUE TITLE
Config.js Not Loading

### ISSUE THREAD

**Issue by TheLamma** [pdlove/homebridge-smartthings#78]
I've been tinkering with getting this setup for a few days now, and after working through numerous installation errors and resetting my pi a couple times, I finally have the homebridge-smartthings plugin working. However, the system doesn't actually load any devices - all I get is this:

Loaded plugin: homebridge-smartthings
Registering platform 'homebridge-smartthings.SmartThings'

And then it goes into "scan this code" etc, etc. 
I have tried several iterations of the json file, both from the readme and the config section on the app, and no dice. Am I missing something? Thanks in advance!

**Comment by Jessassin** [comment]
Have you gone into the app on your phone and allowed it to access the specific devices from your hub?

on your phone:
`app` > `hamburger icon` > `smartapps` > `smartthings-homebridge` 

Then ensure you have selected the devices under "most devices, sensor devices, all switches" that you want to expose.

**Comment by TheLamma** [comment]
I'm a little confused, then - in your Read Me it explains how to download the "JSON Complete API" SmartApp. Is there one called "smartthings-homebridge" that I don't know about? That is the name I see on my pi. 
If they are the same thing, however, I do have devices selected under all three categories.

**Comment by gitstn** [comment]
I am having the same issue. I have the smart app installed and I have allowed the devices in the smartapp.

**Comment by gitstn** [comment]
Here are the logs BTW

[9/16/2016, 5:44:50 AM] Loaded plugin: homebridge-smartthings
[9/16/2016, 5:44:50 AM] Registering platform 'homebridge-smartthings.SmartThings'
[9/16/2016, 5:44:50 AM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

[Code here]

[9/16/2016, 5:44:50 AM] Homebridge is running on port 51826.

**Comment by gitstn** [comment]
NM, for me it started working. It was wrong location of config.json

Thanks for a great project.

**Comment by TheLamma** [comment]
gitstn, would you mind telling me what you found was the right locating/path? I have a feeling that may be my issue, as well - the folders are a labyrinth with similarly named sub-folders.

**Comment by gitstn** [comment]
The right path is the .homebridge sub directory under the user's home
directory where the user is the user id homebridge is running as.
