### ISSUE TITLE
Can't Add 1st gen smartthings motion sensor

### ISSUE THREAD

**Issue by humac** [pdlove/homebridge-smartthings#8]
My first gen motion sensor doesn't seem to appear in the smart app to select

**Comment by pdlove** [comment]
Same ask as on the momentary switch, can you get me a screenshot of the panel in smart things for this device?

**Comment by humac** [comment]
This is what the device type lists in the IDE Device template for capabilities

metadata {
	definition (name: "SmartSense Motion", namespace: "smartthings", author: "SmartThings") {
		capability "Signal Strength"
		capability "Motion Sensor"
		capability "Sensor"
		capability "Battery"

**Comment by humac** [comment]
![image](https://cloud.githubusercontent.com/assets/9813864/12864682/a968448a-cc61-11e5-8e2a-98794872b4e2.png)

**Comment by pdlove** [comment]
Is this one showing now?

**Comment by humac** [comment]
Yep but other motions show up in "most devices" and these show up under "sensor devices"

**Comment by pdlove** [comment]
This should work for you in the other group, let me know if it still isn't.
