### ISSUE TITLE
Testing with iOS 10

### ISSUE THREAD

**Issue by totallymystic** [pdlove/homebridge-smartthings#81]
I've been testing this with iOS 10 recently and it seems to be working sometimes. Forced actions like turning on/off a light works but sometimes it seems the appropriate response isn't sent back to either homebridge or HomeKit. So while the light may turn off, The icon still shows it's on. This has been happening for a few accessories. While I am inclined to think that this may be a Home application issue, I was wondering if anyone checked this out. 

I have Nest homebridge plugin installed and that works perfectly.

**Comment by pdlove** [comment]
After a couple of updates to IOS 10, I'll look further into this. The problem that we have right now is that Apple hasn't really updated the HomeKit Simulator so we can't update the UUIDs to reflect the new requirements yet. Khaost, who has previously handled that part of homebridge can't help us until fall.

The problem with Smartthings vs Nest is that the Smartthings plugin has to handle a very wide range of devices and any issue with any of the UUIDs used for the devices can cause all hosted devices to act screwy.

**Comment by andrewdutoit1978** [comment]
Hi,

I also have this with my door sensors, the updates are not flowing back and it stays open until I reboot homebridge!

Ill dig a little and see what I can find

**Comment by pdlove** [comment]
I'm closing this due to the drastic improvements made. Please let me know if you still experience this issue.
