### ISSUE TITLE
Sorry , name,i didnt hear back

### ISSUE THREAD

**Issue by 5t1tch** [pdlove/homebridge-smartthings#85]
everything has been perfectly for a number of weeks , but recently requesting the temperature of a room 
has suddenly stopped.
the way this was setup was simply adding a smartthings motion sensor to a room using the eve app.
i was able to ask siri what is the tempreture in the hallway , and she would happily respond.
now she replys with "sorry i didnt hear back"
the devices all work as expected visually in eve updating no problem

has anyone else experianced the same issue recently

**Comment by pdlove** [comment]
Is everything working fine from a home kit app?

**Comment by 5t1tch** [comment]
yes everything works as expected in homekit app such as eve or idevices. strangely however the issue has resolved its self i made no changes to the setup. The problem lasted 2-3 days.  so maybe it was an apple/siri problem?
