### ISSUE TITLE
Access Token problem

### ISSUE THREAD

**Issue by partytimeexcellent** [pdlove/homebridge-smartthings#87]
I got everything installed following your directions but I'm receiving this AccessDenied error when I start up homebridge:

[SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[8/2/2016, 4:44:07 AM] [SmartThings] Fetching Smart Things devices.
[8/2/2016, 4:44:08 AM] [SmartThings] Error received type AccessDenied - This request is not authorized by the specified access token
[8/2/2016, 4:44:08 AM] [SmartThings] Unknown Capabilities: []

My app_id and access_token match what I'm seeing in the Smartthings app. Any ideas?

**Comment by partytimeexcellent** [comment]
never mind- looks like the tutorial I followed was linking to an outdated url. I updated the url and its working fine!

**Comment by rcoh80** [comment]
I'm getting the same error. What URL did you update?

**Comment by partytimeexcellent** [comment]
I had this line in my jSON.config from a tutorial. Turns out it's a depreciated link.

app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",

I updated it to this, to match the readout that appears when home ridge starts and it works great:

"app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",

I hope that helps you!

**Comment by rcoh80** [comment]
Brilliant! Thank you, that's done it! I used the EU address though: https://graph-eu01-euwest1.api.smartthings.com:443/api/smartapps/installations/

**Comment by mikeag** [comment]
great this work for me
