### ISSUE TITLE
Refresh List of Devices after install?

### ISSUE THREAD

**Issue by reivax** [pdlove/homebridge-smartthings#88]
Sorry if I missed something obvious but is there an easy way to add new devices after home bridge and the ST plugin is installed? 

I added 6 new outlets but it seems home bridge is not seeing them - In graph.api.smartthings.com I see the devices but haven't found a way to expose the new devices to the homebridge-smart app - any suggestions other than removing and re-installing the app? thanks!

**Comment by tannebil** [comment]
You need to go back into the JSON Complete API, pick the devices, and restart HomeBridge

**Comment by reivax** [comment]
argh thanks a lot - totally missed this was done in the smart app in the Smarthings iOS App and not in the graph.api console.  thanks again!

**Comment by ELLIOTTCABLE** [comment]
This might could use a mention in the README. It was non-obvious for me, too. `(=`
