### ISSUE TITLE
2nd Gen Smart Sense Motion not updating 

### ISSUE THREAD

**Issue by humac** [pdlove/homebridge-smartthings#9]
When I add my 2nd gen smart sense motion it doesn't seem to pick up any motion updates and also the temp stays at 0.0.

**Comment by pdlove** [comment]
I'll check this tonight on my setup.

**Comment by humac** [comment]
seems to update now, but takes about 8 secs

**Comment by humac** [comment]
Today I'm not getting motion updates and my temperature still reads 0.0

**Comment by humac** [comment]
it seems these and my contact sensors have stopped updating...  Not sure from which release it stopped though
