### ISSUE TITLE
This request is not authorized by the specified access token + UK users?

### ISSUE THREAD

**Issue by rcoh80** [pdlove/homebridge-smartthings#90]
I’ve tried to upgrade from the original SmartThings plugin (part of homebridge-legacy-plugins) to this improved version.

I’ve done the install on a different Pi. Homebridge and Homebridge-smartthings have both installed fine and I can see the Homebridge ‘bridge/hub’ in HomeKit. I’ve got the SmartApp on my phone app with devices selected. However, there are no accessories associated with the bridge on HomeKit.

I’m getting the error reported on other threads of:
```
[8/13/2016, 4:38:29 PM] [SmartThings] Error received type AccessDenied - This request is not authorized by the specified access token
[8/13/2016, 4:38:29 PM] [SmartThings] Unknown Capabilities: []
```
(I checked my app_id and access_token)

Also, I’m in the UK. For the original JSON API, I had to change a couple of references for https://graph.api.smartthings.com to https://graph-eu01-euwest1.api.smartthings.com
I’ve tried changing those URLs in the **smartthingsapi.js** file at /usr/local/lib/node_modules/homebridge-smartthings/lib (there’s two instances of the URL) but still no luck.

**Comment by rcoh80** [comment]
Resolved from: https://github.com/pdlove/homebridge-smartthings/issues/87#issuecomment-239631055

**Comment by pdlove** [comment]
If you hit the config button in the smartapp then it should have provided the correct we address.

**Comment by dansingha** [comment]
When Smartthings API generates URL, it gives you its server based  URL.( https://graph.api.smarthings.com/) You have to take a look at your Smartthings API URL address up on the browser address bar. In the US it should be  https://graph-**na02-useast1.**api.smartthings.com/
