### ISSUE TITLE
Having an issue adding from the UK

### ISSUE THREAD

**Issue by miguelmolez** [pdlove/homebridge-smartthings#91]
Hi,

I don't seem to be able to add the repo from the 'my smart aps' page from the UK
https://graph-eu01-euwest1.api.smartthings.com/

Is there a work around for this until we have the full functionality over here?

Thanks

**Comment by ciscosurplus** [comment]
Having the same issue, the setup looks different I tried a few combinations but can't seem to find the correct way to add it.

**Comment by miguelmolez** [comment]
I've managed to find a work around by following the process on the US site, then manually copying the code over to https://graph-eu01-euwest1.api.smartthings.com/ 
Works a treat!
Let me know if you need me to talk you through it. 

M

**Comment by RickStirling** [comment]
Hey Miguel, it's be great if you could post a step by step.

I logged into the US graph and created the smartapp there, I think I just need to copy the raw code over the EU version, then update a URL?

**Comment by pdlove** [comment]
I'll update with instructions on how to do it without using the github repo on the site. It looks like they don't support using a repository on their EU servers for some reason.

**Comment by ciscosurplus** [comment]
@miguelmolez do you just copy the code at this step "In the SmartThings App, goto "Marketplace" and select "SmartApps". At the bottom of the list, select "My Apps"

Then copy the code over and revert to following from that step on in the EU server? It won't let me publish for some reason so it isn't appearing in the marketplace for me.

**Comment by RickStirling** [comment]
Hey Cisco, I just tried the copy and publish and that worked fine for me. I can see the app in my EU Smartthings App list (alongside the legacy ST app), and I was able to authorise the OAuth too.

I've not tried hooking it up in the ST app yet since I'm not at home.

**Comment by pdlove** [comment]
I updated the instructions to include how to copy/paste the smartapp. I've also reached out to my contact to find out why the Europe servers aren't able to use github.

**Comment by pinion** [comment]
I can't see your specific instructions and there is still no UK support.
Can you link to your updated instructions?
