### ISSUE TITLE
HomeKit sees only first 5 devices

### ISSUE THREAD

**Issue by neelroy** [pdlove/homebridge-smartthings#92]
Hi - first of all, thank you on working to integrate SmartThings and HomeKit. I was able to get everything up and running, all 17 devices show being added and initialized during startup.

But for some reason it shows me only the first 5 devices (alphabetically) in Eve (or any other HomeKit app).

Please let me know if you have any ideas why this could be happening.

Thanks.

**Comment by neelroy** [comment]
So, I was able to resolve this by deselecting the sixth device in the JSON API SmartApp and then everything behind it was able show up in HomeKit. As for the sixth device, which Is a lock, is an issue for another day.

**Comment by pdlove** [comment]
Are you on IOS 10? Before that we hadn't previously had issues with locks.

**Comment by neelroy** [comment]
Not yet. might be a bad lock.
