### ISSUE TITLE
Correction to instructions

### ISSUE THREAD

**Issue by ashman5555** [pdlove/homebridge-smartthings#95]
I got hung up on the following paragraph.

"To get this information, open SmartThings on your phone, goto "My Home">"SmartApps">"JSON Complete API" and tap on Config polling_seconds is optional and defaults to 60. update_seconds is optional and defaults to 1. At this speed, updates feel instant, but it can be reduced to 0.5 or increased up to 60."

I think there should be a period after Config and before polling.
Also, "My Home">"SmartApps">"JSON Complete API" is no longer correct for iOS.
It is now "Automations">"SmartApps">"JSON Complete API".

I offer this revision:

To get this information,
- Open SmartThings on your phone, 
- Goto "Automations">"SmartApps">"JSON Complete API",
- Tap on Config,
- Copy and Paste "app_id" and "access_token" into config.json

NOTE:
"polling_seconds" is optional and defaults to 60
"update_seconds" is optional and defaults to 1
 At these "default" times, updates feel instant, but it can be reduced to 0.5 or increased up to 60.

**Comment by pdlove** [comment]
The documentation has been revamped since this was posted.
