### ISSUE TITLE
Settings for JSON Api App not saving

### ISSUE THREAD

**Issue by venumx** [pdlove/homebridge-smartthings#98]
When trying to check my devices in the My Apps > JSON Complete API > Most devices then press Done > Done, then go back in the settings did not save. Also everytime i go back into it, it generates new "config" so the appid and token keep changing.

**Comment by bs** [comment]
Confirmed that I'm seeing this as well.

**Comment by realdannys** [comment]
Me too...

**Comment by holden777** [comment]
Same thing. Every time I go to settings the codes change so homebridge can not connect.

**Comment by derrick-smith** [comment]
Unfortunately.  Same for me as well.

**Comment by alecm** [comment]
Ok - I *think* I figured it out - at least got it working for me.  

Apparently every time you go to the "JSON Complete API" app under "Marketplace --> SmartApps" you are creating a new instance from scratch - so of course it doesn't remember settings and it creates new tokens.

The trick for me was
1.  In Smartthings IDE 
      a. click on  "My Locations", 
      b. Over to the right there is a column "Installed SmartApps"
      c. Click on "smartapps" for your location
      d. When list comes up, click on "Edit" at top right under your location image
      e. All should switch from "Update" to  "Uninstall"
      f. Look for all instances of "JSON Complete API"
      g. Uninstall them all  - THIS WILL DELETE YOUR CURRENT HomeBridge settings - (that's what I did, because I had a simple setup so would rather start from  scratch -
IF YOU HAVE SOMETHING COMPLEX YOU'RE TRYING TO SALVAGE  you may try looking at the details for each one and seeing if there's one you'd like to try to keep - just hover over the "uninstall" and it will show you what's attached - up to you if you want to try to save one - I did not specifically test this).
      h. Hit "Done" at top to save the changes

In SmartThings App:
IF YOU DELETED ALL:
 a.  MarketPlace/ Smart Apps/ My Apps (near bottom)
 b.  Start up the JSON Complete API,  make your selections, etc.
 c. 'Done''
 d.  Go to Automations/SmartApps
 - You should now see an instance there with what you selected  - use the Config from _this_ one to update your Config.jsn file tokens
- This instance can now be updated, selections changed, etc.  without changing tokens
- Do NOT go to Marketplace/ Smart Apps to make changes - you'll be creating a new instance!

[Note I've found that I always have to stop and restart HomeBridge when I make any selection changes  - and have usually had to readd them to rooms, etc. ]

IF YOU KEPT ONE IN THE IDE 
Start w/ Step d. above and see if it kept your setup - make sure you update the config.fl file with the tokens in this one's config.  (AGAIN - I DID NOT TEST THIS - JUST SUGGESTING A POSSIBLE WAY TO SALVAGE a COMPLEX SETUP). 

Hope this works for others -this spawning of instances drove me nuts!
